// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.*;

public class ExceptionHandlerHelper_getInstance_292da993d8_Test {

    @InjectMocks
    private ExceptionHandlerHelper exceptionHandlerHelper;
    
    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetInstance_NotNull() {
        ExceptionHandlerHelper instance = ExceptionHandlerHelper.getInstance();
        assertNotNull(instance, "Instance should not be null");
    }
    
    @Test
    public void testGetInstance_SameInstance() {
        ExceptionHandlerHelper instance1 = ExceptionHandlerHelper.getInstance();
        ExceptionHandlerHelper instance2 = ExceptionHandlerHelper.getInstance();
        assertSame(instance1, instance2, "Instances should be the same");
    }
}
