// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.exception;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.io.Writer;

@RunWith(MockitoJUnitRunner.class)
public class ExceptionLogger_getStackTrace_a9ec437fca_Test {

    private ExceptionLogger exceptionLogger;

    @Before
    public void setup() {
        exceptionLogger = new ExceptionLogger();
    }

    @Test
    public void testGetStackTrace() {
        Exception exception = new Exception("Test exception");
        String stackTrace = exceptionLogger.getStackTrace(exception);

        assertTrue(stackTrace.contains("Exception: Test exception"));
        assertTrue(stackTrace.contains("at org.camunda.bpm.engine.rest.exception.ExceptionLogger_getStackTrace_a9ec437fca_Test.testGetStackTrace"));
    }

    @Test
    public void testGetStackTrace_NullException() {
        String stackTrace = exceptionLogger.getStackTrace(null);

        assertEquals("", stackTrace);
    }
}
