// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.exception;

import org.camunda.bpm.engine.ProcessEngineException;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class ExceptionHandlerHelper_getCode_8d4d32b729_Test {

    @Mock
    private ProcessEngineException mockProcessEngineException;

    private ExceptionHandlerHelper exceptionHandlerHelper;

    @Before
    public void setUp() {
        exceptionHandlerHelper = new ExceptionHandlerHelper();
    }

    @Test
    public void testGetCode_Success() {
        // TODO: Replace with the actual error code
        Integer expectedErrorCode = 123;
        when(mockProcessEngineException.getCode()).thenReturn(expectedErrorCode);

        Integer actualErrorCode = exceptionHandlerHelper.getCode(mockProcessEngineException);

        assertEquals(expectedErrorCode, actualErrorCode);
    }

    @Test(expected = ClassCastException.class)
    public void testGetCode_WithNonProcessEngineException() {
        Throwable nonProcessEngineException = new Exception("Non ProcessEngineException");
        exceptionHandlerHelper.getCode(nonProcessEngineException);
    }
}
