// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.*;

public class ExceptionHandlerHelper_ExceptionHandlerHelper_eadbd1e8d5_Test {

    @InjectMocks
    ExceptionHandlerHelper exceptionHandlerHelper;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testPrivateConstructor() throws Exception {
        try {
            ExceptionHandlerHelper.class.getDeclaredConstructor().newInstance();
            fail("Expected IllegalAccessException.class");
        } catch (Exception ex) {
            assertTrue(ex instanceof IllegalAccessException);
        }
    }

    @Test
    public void testPrivateConstructorAccessible() throws Exception {
        try {
            ExceptionHandlerHelper.class.getDeclaredConstructor().setAccessible(true);
            fail("Expected InvocationTargetException.class");
        } catch (Exception ex) {
            assertTrue(ex instanceof InvocationTargetException);
        }
    }
}
