// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class ExceptionHandlerHelper_provideExceptionCode_9b6591edab_Test {

    private ExceptionHandlerHelper exceptionHandlerHelper;
    private ExceptionDto exceptionDto;

    @BeforeEach
    public void setUp() {
        exceptionHandlerHelper = new ExceptionHandlerHelper();
        exceptionDto = new ExceptionDto();
    }

    @Test
    public void testProvideExceptionCode_ProcessEngineException() {
        Throwable throwable = Mockito.mock(ProcessEngineException.class);
        when(exceptionHandlerHelper.getCode(throwable)).thenReturn(1234);
        exceptionHandlerHelper.provideExceptionCode(throwable, exceptionDto);
        assertEquals(1234, exceptionDto.getCode());
    }

    @Test
    public void testProvideExceptionCode_RestException() {
        Throwable cause = Mockito.mock(ProcessEngineException.class);
        Throwable throwable = new RestException(cause);
        when(exceptionHandlerHelper.getCode(cause)).thenReturn(1234);
        exceptionHandlerHelper.provideExceptionCode(throwable, exceptionDto);
        assertEquals(1234, exceptionDto.getCode());
    }

    @Test
    public void testProvideExceptionCode_OtherException() {
        Throwable throwable = Mockito.mock(Throwable.class);
        exceptionHandlerHelper.provideExceptionCode(throwable, exceptionDto);
        assertEquals(null, exceptionDto.getCode());
    }
}
