// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.exception;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import javax.ws.rs.core.Response;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.camunda.bpm.engine.rest.dto.RestException;

public class ExceptionHandlerHelper_getStatus_a95e607cbf_Test {

    private ExceptionHandlerHelper exceptionHandlerHelper;
    private RestException restException;

    @BeforeEach
    public void setUp() {
        exceptionHandlerHelper = new ExceptionHandlerHelper();
        restException = mock(RestException.class);
    }

    @Test
    public void testGetStatus_WhenStatusNotNull() {
        when(restException.getStatus()).thenReturn(Response.Status.BAD_REQUEST);
        Response.Status status = exceptionHandlerHelper.getStatus(restException);
        assertEquals(Response.Status.BAD_REQUEST, status);
    }

    @Test
    public void testGetStatus_WhenStatusNull() {
        when(restException.getStatus()).thenReturn(null);
        Response.Status status = exceptionHandlerHelper.getStatus(restException);
        assertEquals(Response.Status.INTERNAL_SERVER_ERROR, status);
    }
}
