// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.exception;

import javax.ws.rs.core.Response.Status;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class InvalidRequestException_InvalidRequestException_43ed2fb4ed_Test {

    @Mock
    private Exception cause;

    private InvalidRequestException invalidRequestException;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testInvalidRequestExceptionWithValidStatus() {
        invalidRequestException = new InvalidRequestException(Status.OK, cause, "Test Message");
        assertNotNull(invalidRequestException);
        assertEquals(Status.OK, invalidRequestException.getStatus());
        assertEquals(cause, invalidRequestException.getCause());
        assertEquals("Test Message", invalidRequestException.getMessage());
    }

    @Test
    public void testInvalidRequestExceptionWithNullStatus() {
        invalidRequestException = new InvalidRequestException(null, cause, "Test Message");
        assertNotNull(invalidRequestException);
        assertEquals(null, invalidRequestException.getStatus());
        assertEquals(cause, invalidRequestException.getCause());
        assertEquals("Test Message", invalidRequestException.getMessage());
    }
}
