// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.exception;

import javax.ws.rs.core.Response.Status;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class InvalidRequestException_InvalidRequestException_f9e7f89f59_Test {

    private InvalidRequestException invalidRequestException;

    @BeforeEach
    public void setup() {
        invalidRequestException = Mockito.mock(InvalidRequestException.class, Mockito.CALLS_REAL_METHODS);
    }

    @Test
    public void testInvalidRequestException_Success() {
        Status status = Status.BAD_REQUEST;
        String message = "Invalid request";

        Mockito.doCallRealMethod().when(invalidRequestException).<Status>super(status, message);
        invalidRequestException.InvalidRequestException(status, message);

        assertEquals(status, invalidRequestException.getStatus());
        assertEquals(message, invalidRequestException.getMessage());
    }

    @Test
    public void testInvalidRequestException_Failure() {
        Status status = Status.BAD_REQUEST;
        String message = "Invalid request";

        Mockito.doCallRealMethod().when(invalidRequestException).<Status>super(status, "Different message");
        invalidRequestException.InvalidRequestException(status, message);

        assertNotEquals(message, invalidRequestException.getMessage());
    }
}
