// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.exception;

import javax.ws.rs.core.Response.Status;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class RestException_getStatus_e72096bbf4_Test {

    @InjectMocks
    private RestException restException;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetStatusSuccess() {
        Status expectedStatus = Status.OK;
        restException.setStatus(expectedStatus);
        Status actualStatus = restException.getStatus();
        assertEquals(expectedStatus, actualStatus);
    }

    @Test
    public void testGetStatusFailure() {
        Status expectedStatus = Status.INTERNAL_SERVER_ERROR;
        restException.setStatus(expectedStatus);
        Status actualStatus = restException.getStatus();
        assertEquals(expectedStatus, actualStatus);
    }
}
