// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.exception;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.MockitoAnnotations;

public class RestException_RestException_51cf441c95_Test {

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testRestException_withValidMessage() {
        String message = "This is a test message";
        RestException restException = new RestException(message);
        assertEquals(message, restException.getMessage());
    }

    @Test
    public void testRestException_withEmptyMessage() {
        String message = "";
        RestException restException = new RestException(message);
        assertEquals(message, restException.getMessage());
    }

    @Test
    public void testRestException_withNullMessage() {
        String message = null;
        RestException restException = new RestException(message);
        assertEquals(message, restException.getMessage());
    }
}
