// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.exception;

import javax.ws.rs.core.Response.Status;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class RestException_RestException_91c6795c63_Test {

    @Mock
    Exception mockException;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testRestException_success() {
        RestException restException = new RestException(Status.OK, mockException);
        assertEquals(Status.OK, restException.getStatus());
        assertEquals(mockException, restException.getCause());
    }

    @Test
    public void testRestException_failure() {
        RestException restException = new RestException(Status.INTERNAL_SERVER_ERROR, mockException);
        assertEquals(Status.INTERNAL_SERVER_ERROR, restException.getStatus());
        assertEquals(mockException, restException.getCause());
    }
}
