// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import java.util.Collections;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class EmptyHalCollection_emptyHalCollection_007ef0c7d3_Test {

    @Test
    public void testEmptyHalCollection_Instance() {
        HalCollectionResource result = EmptyHalCollection.emptyHalCollection();
        assertTrue(result instanceof EmptyHalCollection, "The method did not return an instance of EmptyHalCollection");
    }

    @Test
    public void testEmptyHalCollection_EmptyCollection() {
        HalCollectionResource result = EmptyHalCollection.emptyHalCollection();
        assertEquals(Collections.emptyList(), result.getEmbedded(), "The method did not return an empty collection");
    }
}
