// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class EmptyHalCollection_EmptyHalCollection_8955d5b9ae_Test {

    private EmptyHalCollection emptyHalCollection;

    @BeforeEach
    public void setup() {
        emptyHalCollection = new EmptyHalCollection();
    }

    @Test
    public void testEmptyHalCollectionWithZero() {
        int expected = 0;
        int actual = emptyHalCollection.size();
        assertEquals(expected, actual, "The size of EmptyHalCollection should be 0");
    }

    @Test
    public void testEmptyHalCollectionAfterAddingElement() {
        emptyHalCollection.add(new Object());
        int expected = 1;
        int actual = emptyHalCollection.size();
        assertEquals(expected, actual, "The size of EmptyHalCollection should be 1 after adding an element");
    }
}
