// Test regenerated by AI

package org.camunda.bpm.engine.rest.hal;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class EmptyHalResource_emptyHalResource_6661469897_Test {

    @MockBean
    private HalResource INSTANCE;

    @BeforeEach
    public void setUp() {
        INSTANCE = new HalResource();
    }

    @Test
    public void testEmptyHalResource_successCase() {
        HalResource actual = HalResource.emptyHalResource();
        assertEquals(INSTANCE, actual, "The actual output does not match the expected output");
    }

    @Test
    public void testEmptyHalResource_failureCase() {
        HalResource actual = HalResource.emptyHalResource();
        HalResource unexpected = new HalResource();
        assertEquals(unexpected, actual, "The actual output should not match the unexpected output");
    }
}
