// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertTrue;

@ExtendWith(MockitoExtension.class)
@SpringBootTest
public class EmptyHalResource_emptyHalResource_6661469897_Test {

    private HalResource halResource;

    @BeforeEach
    public void setUp() {
        halResource = HalResource.emptyHalResource();
    }

    @Test
    public void testEmptyHalResource_instanceOfHalResource() {
        assertTrue(halResource instanceof HalResource);
    }

    @Test
    public void testEmptyHalResource_sameInstance() {
        HalResource anotherHalResource = HalResource.emptyHalResource();
        assertTrue(halResource == anotherHalResource);
    }
}
