// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;

class Hal_getInstance_e3551bda1d_Test {

    private Hal instance;

    @BeforeEach
    public void setUp() {
        instance = Hal.getInstance();
    }

    @Test
    public void testGetInstance_notNull() {
        Assertions.assertNotNull(instance, "Instance should not be null");
    }

    @Test
    public void testGetInstance_sameInstance() {
        Hal anotherInstance = Hal.getInstance();
        Assertions.assertSame(instance, anotherInstance, "Instances should be the same");
    }
}
