// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import java.util.HashMap;
import java.util.Map;
import org.camunda.bpm.engine.rest.cache.Cache;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.boot.test.context.SpringBootTest;

@RunWith(MockitoJUnitRunner.class)
@SpringBootTest
public class Hal_destroyHalRelationCaches_68c296a659_Test {

    private Map<String, Cache> halRelationCaches;

    @Mock
    private Cache cache;

    @Before
    public void setUp() {
        halRelationCaches = new HashMap<>();
        halRelationCaches.put("cache1", cache);
        halRelationCaches.put("cache2", cache);
    }

    @Test
    public void testDestroyHalRelationCaches() {
        for (Cache cache : halRelationCaches.values()) {
            cache.destroy();
        }
        halRelationCaches.clear();

        Mockito.verify(cache, Mockito.times(2)).destroy();
        assert(halRelationCaches.isEmpty());
    }

    @Test(expected = NullPointerException.class)
    public void testDestroyHalRelationCachesWhenCacheIsNull() {
        halRelationCaches.put("cache3", null);
        for (Cache cache : halRelationCaches.values()) {
            cache.destroy();
        }
    }
}
