// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class Hal_registerHalRelationCache_bf15f1c592_Test {

    private Map<Class<?>, Cache> halRelationCaches;
    private Cache cache;

    @BeforeEach
    public void setUp() {
        halRelationCaches = new HashMap<>();
        cache = Mockito.mock(Cache.class);
    }

    @Test
    public void testRegisterHalRelationCache_Success() {
        Class<?> entityClass = String.class;
        registerHalRelationCache(entityClass, cache);
        assertTrue(halRelationCaches.containsKey(entityClass));
        assertEquals(cache, halRelationCaches.get(entityClass));
    }

    @Test
    public void testRegisterHalRelationCache_NullEntityClass() {
        assertThrows(NullPointerException.class, () -> registerHalRelationCache(null, cache));
    }

    public void registerHalRelationCache(Class<?> entityClass, Cache cache) {
        halRelationCaches.put(entityClass, cache);
    }
}
