// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.HashMap;
import java.util.Map;

import org.camunda.bpm.engine.rest.cache.Cache;
import org.junit.Before;
import org.junit.Test;

public class Hal_getHalRelationCache_9a92ebb15d_Test {

  private Map<Class<?>, Cache> halRelationCaches;
  private Hal hal;

  @Before
  public void setUp() {
    halRelationCaches = new HashMap<>();
    hal = new Hal();
    hal.halRelationCaches = this.halRelationCaches;
  }

  @Test
  public void testGetHalRelationCache_Success() {
    // Mocking
    Class<?> resourceClass = UserRestService.class;
    Cache cache = mock(Cache.class);
    halRelationCaches.put(resourceClass, cache);

    // Execution
    Cache result = hal.getHalRelationCache(resourceClass);

    // Assertion
    assertEquals(cache, result);
  }

  @Test
  public void testGetHalRelationCache_Failure() {
    // Mocking
    Class<?> resourceClass = GroupRestService.class;

    // Execution
    Cache result = hal.getHalRelationCache(resourceClass);

    // Assertion
    assertEquals(null, result);
  }
}
