// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class Hal_createLinker_c125a90c3a_Test {

    @Mock
    private HalResource<?> resource;

    private HalLinker halLinker;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        halLinker = new HalLinker();
    }

    @Test
    public void testCreateLinkerSuccess() {
        HalLinker result = halLinker.createLinker(resource);
        assertNotNull(result);
        assertSame(halLinker, result.getHalLinker());
        assertSame(resource, result.getResource());
    }

    @Test
    public void testCreateLinkerNullResource() {
        HalLinker result = halLinker.createLinker(null);
        assertNotNull(result);
        assertSame(halLinker, result.getHalLinker());
        assertNull(result.getResource());
    }
}
