// Test regenerated by Assistant for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import java.util.HashMap;
import java.util.Map;
import org.camunda.bpm.engine.rest.cache.Cache;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;

@RunWith(SpringRunner.class)
@SpringBootTest
public class Hal_getHalRelationCache_9a92ebb15d_Test {

    private Map<Class<?>, Cache> halRelationCaches;

    @Before
    public void setUp() {
        halRelationCaches = new HashMap<>();
        Cache mockCache = mock(Cache.class);
        halRelationCaches.put(String.class, mockCache);
    }

    @Test
    public void testGetHalRelationCache_Success() {
        Cache result = getHalRelationCache(String.class);
        assertEquals(halRelationCaches.get(String.class), result);
    }

    @Test
    public void testGetHalRelationCache_Failure() {
        Cache result = getHalRelationCache(Integer.class);
        assertEquals(null, result);
    }

    public Cache getHalRelationCache(Class<?> resourceClass) {
        return halRelationCaches.get(resourceClass);
    }
}
