// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class HalLink_getHref_241b8e9eb9_Test {

    @InjectMocks
    private HalLink halLink;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
        halLink.setHref("http://example.com");
    }

    @Test
    public void testGetHref_Success() {
        String expectedHref = "http://example.com";
        String actualHref = halLink.getHref();
        assertEquals(expectedHref, actualHref, "The expected href does not match the actual href.");
    }

    @Test
    public void testGetHref_Failure() {
        String expectedHref = "http://wrong.example.com";
        String actualHref = halLink.getHref();
        assertEquals(expectedHref, actualHref, "The expected href does not match the actual href.");
    }
}
