// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class HalLink_HalLink_68520a641e_Test {

    private HalLink halLink;

    @BeforeEach
    public void setUp() {
        halLink = new HalLink("http://localhost:8080");
    }

    @Test
    public void testHalLinkConstructorWithCorrectHref() {
        assertEquals("http://localhost:8080", halLink.getHref(), "Href should match the one passed to the constructor");
    }

    @Test
    public void testHalLinkConstructorWithNullHref() {
        Exception exception = assertThrows(NullPointerException.class, () -> {
            new HalLink(null);
        });
        String expectedMessage = "Href cannot be null";
        String actualMessage = exception.getMessage();
        assertEquals(expectedMessage, actualMessage, "Exception message should be correct");
    }
}
