// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

import java.util.Map;
import java.util.TreeMap;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@SpringBootTest
public class HalResource_get_embedded_162d718460_Test {

    @MockBean
    private HalResource halResource;

    private Map<String, Object> _embedded;

    @BeforeEach
    public void setUp() {
        _embedded = new TreeMap<>();
        _embedded.put("key1", "value1");
        _embedded.put("key2", "value2");
    }

    @Test
    public void testGetEmbeddedSuccess() {
        when(halResource.get_embedded()).thenReturn(_embedded);

        Map<String, Object> result = halResource.get_embedded();

        assertEquals(_embedded, result);
    }

    @Test
    public void testGetEmbeddedEmpty() {
        _embedded.clear();
        when(halResource.get_embedded()).thenReturn(_embedded);

        Map<String, Object> result = halResource.get_embedded();

        assertEquals(_embedded, result);
    }
}
