// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;

import javax.ws.rs.core.UriBuilder;

import org.junit.Before;
import org.junit.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class HalRelation_build_caaadaf711_Test {

    private Class<?> resourceType;
    private UriBuilder urlTemplate;
    private String relName;

    @Before
    public void setUp() {
        resourceType = mock(Class.class); // TODO: Replace with actual class
        urlTemplate = mock(UriBuilder.class); // TODO: Replace with actual UriBuilder
        relName = "relationName";
    }

    @Test
    public void testBuild_Success() {
        HalRelation relation = HalRelation.build(relName, resourceType, urlTemplate);
        assertEquals(relName, relation.getRelName());
        assertEquals(resourceType, relation.getResourceType());
        assertEquals(urlTemplate, relation.getUriTemplate());
    }

    @Test(expected = NullPointerException.class)
    public void testBuild_NullRelName() {
        HalRelation.build(null, resourceType, urlTemplate);
    }

    @Test(expected = NullPointerException.class)
    public void testBuild_NullResourceType() {
        HalRelation.build(relName, null, urlTemplate);
    }

    @Test(expected = NullPointerException.class)
    public void testBuild_NullUrlTemplate() {
        HalRelation.build(relName, resourceType, null);
    }
}
