// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import javax.ws.rs.core.UriBuilder;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class HalRelation_getUriTemplate_cc65a9ad39_Test {

    private UriBuilder uriTemplate;
    private HalRelation halRelation;

    @BeforeEach
    public void setup() {
        uriTemplate = mock(UriBuilder.class);
        halRelation = new HalRelation(uriTemplate);
    }

    @Test
    public void testGetUriTemplate_Success() {
        UriBuilder expectedUriTemplate = UriBuilder.fromPath("/test/path");
        when(uriTemplate.clone()).thenReturn(expectedUriTemplate);

        UriBuilder actualUriTemplate = halRelation.getUriTemplate();

        assertEquals(expectedUriTemplate, actualUriTemplate);
    }

    @Test
    public void testGetUriTemplate_Null() {
        when(uriTemplate.clone()).thenReturn(null);

        UriBuilder actualUriTemplate = halRelation.getUriTemplate();

        assertEquals(null, actualUriTemplate);
    }
}
