// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class HalRelation_getRelName_9ef30b4c71_Test {

    private HalRelation halRelation;

    @BeforeEach
    public void setUp() {
        halRelation = Mockito.mock(HalRelation.class);
        Mockito.when(halRelation.getRelName()).thenReturn("relationName");
    }

    @Test
    public void testGetRelName_Success() {
        String expectedRelName = "relationName";
        String actualRelName = halRelation.getRelName();
        assertEquals(expectedRelName, actualRelName, "Expected relation name does not match actual relation name");
    }

    @Test
    public void testGetRelName_Failure() {
        String unexpectedRelName = "unexpectedRelationName";
        String actualRelName = halRelation.getRelName();
        assertNotEquals(unexpectedRelName, actualRelName, "Unexpected relation name matches actual relation name");
    }
}
