// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class HalResource_addLink_844c77f4a6_Test {

    private HalResource halResource;

    @BeforeEach
    public void setUp() {
        halResource = new HalResource();
    }

    @Test
    public void testAddLink() {
        String rel = "self";
        String href = "http://localhost:8080/test";
        halResource.addLink(rel, href);
        Map<String, HalLink> links = halResource.get_links();
        assertNotNull(links);
        HalLink link = links.get(rel);
        assertNotNull(link);
        assertEquals(href, link.getHref());
    }

    @Test
    public void testAddLinkWithNullLinks() {
        String rel = "self";
        String href = "http://localhost:8080/test";
        halResource.set_links(null);
        halResource.addLink(rel, href);
        Map<String, HalLink> links = halResource.get_links();
        assertNotNull(links);
        HalLink link = links.get(rel);
        assertNotNull(link);
        assertEquals(href, link.getHref());
    }
}
