// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import org.camunda.bpm.engine.rest.ProcessInstanceRestService;
import org.camunda.bpm.engine.rest.dto.VariableValueDto;
import org.camunda.bpm.engine.runtime.VariableInstance;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class HalVariableValue_generateProcessInstanceVariableValue_6d57ac85f3_Test {

    @Mock
    private VariableInstance variableInstance;

    private String processInstanceId = "testProcessInstanceId";

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGenerateProcessInstanceVariableValue_Success() {
        HalVariableValue halVariableValue = HalVariableValue.fromVariableInstance(variableInstance);
        halVariableValue.link(HalVariableValue.REL_SELF, ProcessInstanceRestService.PATH, processInstanceId, "variables");

        HalVariableValue result = HalVariableValue.generateProcessInstanceVariableValue(variableInstance, processInstanceId);

        assertEquals(halVariableValue, result);
    }

    @Test
    public void testGenerateProcessInstanceVariableValue_NullVariableInstance() {
        HalVariableValue result = HalVariableValue.generateProcessInstanceVariableValue(null, processInstanceId);
        assertEquals(null, result);
    }
}
