// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal;

import org.camunda.bpm.engine.rest.*;
import org.camunda.bpm.engine.rest.dto.VariableValueDto;
import org.camunda.bpm.engine.rest.exception.RestException;
import org.camunda.bpm.engine.rest.sub.VariableResource;
import org.camunda.bpm.engine.runtime.VariableInstance;
import javax.ws.rs.core.UriBuilder;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(MockitoExtension.class)
public class HalVariableValue_generateCaseInstanceVariableValue_513251f6fd_Test {

    @Mock
    private VariableInstance variableInstance;

    private String caseInstanceId;

    @BeforeEach
    public void setUp() {
        caseInstanceId = "testId";  // TODO: Replace with actual case instance id
    }

    @Test
    public void testGenerateCaseInstanceVariableValue_Success() {
        HalVariableValue result = HalVariableValue.generateCaseInstanceVariableValue(variableInstance, caseInstanceId);
        assertNotNull(result);
        assertEquals(caseInstanceId, result.getCaseInstanceId());
    }

    @Test
    public void testGenerateCaseInstanceVariableValue_NullVariableInstance() {
        assertThrows(NullPointerException.class, () -> HalVariableValue.generateCaseInstanceVariableValue(null, caseInstanceId));
    }

    @Test
    public void testGenerateCaseInstanceVariableValue_NullCaseInstanceId() {
        assertThrows(NullPointerException.class, () -> HalVariableValue.generateCaseInstanceVariableValue(variableInstance, null));
    }
}
