// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal.cache;

import org.camunda.bpm.engine.rest.cache.Cache;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.times;

public class DefaultHalResourceCache_remove_95487decfa_Test {

    @Mock
    private Cache cache;

    private DefaultHalResourceCache defaultHalResourceCache;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        defaultHalResourceCache = new DefaultHalResourceCache();
    }

    @Test
    public void testRemove_withValidId() {
        String validId = "12345";
        defaultHalResourceCache.remove(validId);
        verify(cache, times(1)).remove(validId);
    }

    @Test
    public void testRemove_withNullId() {
        String nullId = null;
        defaultHalResourceCache.remove(nullId);
        verify(cache, times(1)).remove(nullId);
    }
}
