// Test generated by RoostGPT for test camunda-new using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal.cache;

import static org.junit.Assert.assertEquals;
import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

public class DefaultHalResourceCache_setCapacity_9137ec4caf_Test {

    @InjectMocks
    private DefaultHalResourceCache defaultHalResourceCache;

    @Before
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetCapacity() {
        int expectedCapacity = 100;
        defaultHalResourceCache.setCapacity(expectedCapacity);
        assertEquals(expectedCapacity, defaultHalResourceCache.getCapacity());
    }

    @Test
    public void testSetCapacityWithZero() {
        int expectedCapacity = 0;
        defaultHalResourceCache.setCapacity(expectedCapacity);
        assertEquals(expectedCapacity, defaultHalResourceCache.getCapacity());
    }

    @Test(expected = IllegalArgumentException.class)
    public void testSetCapacityWithNegativeNumber() {
        int expectedCapacity = -10;
        defaultHalResourceCache.setCapacity(expectedCapacity);
    }
}
