// Test generated by RoostGPT for test camunda-new using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.hal.cache;

import static org.mockito.Mockito.*;
import javax.servlet.ServletContext;
import javax.servlet.ServletContextEvent;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class HalRelationCacheBootstrap_contextInitialized_196b428546_Test {

    private static final String CONTEXT_PARAM_NAME = "cacheParam";

    @InjectMocks
    HalRelationCacheBootstrap halRelationCacheBootstrap;

    @Mock
    ServletContextEvent sce;

    @Mock
    ServletContext context;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testContextInitialized_withContextParameter() {
        when(sce.getServletContext()).thenReturn(context);
        when(context.getInitParameter(CONTEXT_PARAM_NAME)).thenReturn("testParam");
        halRelationCacheBootstrap.contextInitialized(sce);
        verify(halRelationCacheBootstrap, times(1)).configureCaches("testParam");
    }

    @Test
    public void testContextInitialized_withoutContextParameter() {
        when(sce.getServletContext()).thenReturn(context);
        when(context.getInitParameter(CONTEXT_PARAM_NAME)).thenReturn(null);
        halRelationCacheBootstrap.contextInitialized(sce);
        verify(halRelationCacheBootstrap, times(0)).configureCaches(anyString());
    }
}
