// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.filter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import javax.servlet.FilterConfig;
import javax.servlet.ServletException;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.*;

public class AbstractEmptyBodyFilter_init_00722f0ee6_Test {

    @Mock
    private FilterConfig filterConfig;

    private AbstractEmptyBodyFilter abstractEmptyBodyFilter;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
        abstractEmptyBodyFilter = new AbstractEmptyBodyFilter();
    }

    @Test
    public void testInit_Success() throws ServletException {
        doNothing().when(filterConfig).getFilterName();
        abstractEmptyBodyFilter.init(filterConfig);
        verify(filterConfig, times(1)).getFilterName();
    }

    @Test
    public void testInit_ThrowsServletException() throws ServletException {
        doThrow(ServletException.class).when(filterConfig).getFilterName();
        assertThrows(ServletException.class, () -> abstractEmptyBodyFilter.init(filterConfig));
        verify(filterConfig, times(1)).getFilterName();
    }
}
