// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.filter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.springframework.mock.web.MockFilterConfig;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;

import javax.servlet.ServletException;

import static org.junit.jupiter.api.Assertions.*;

class CacheControlFilter_destroy_1568201276_Test {

    @InjectMocks
    private CacheControlFilter cacheControlFilter;

    private MockHttpServletRequest request;
    private MockHttpServletResponse response;

    @BeforeEach
    public void setUp() throws ServletException {
        MockitoAnnotations.openMocks(this);
        request = new MockHttpServletRequest();
        response = new MockHttpServletResponse();
        cacheControlFilter.init(new MockFilterConfig());
    }

    @Test
    public void testDestroy() {
        assertDoesNotThrow(() -> cacheControlFilter.destroy());
    }

    @Test
    public void testDestroyAfterFilter() throws ServletException {
        cacheControlFilter.doFilter(request, response, null);
        assertDoesNotThrow(() -> cacheControlFilter.destroy());
    }
}
