// Test generated by RoostGPT for test camuda-engine-test using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.engine.rest.filter;

import javax.servlet.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;

public class CacheControlFilter_init_00722f0ee6_Test {

    @Mock
    private FilterConfig filterConfig;

    private CacheControlFilter cacheControlFilter;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
        cacheControlFilter = new CacheControlFilter();
    }

    @Test
    public void testInit_withValidFilterConfig() {
        assertDoesNotThrow(() -> cacheControlFilter.init(filterConfig));
    }

    @Test
    public void testInit_withNullFilterConfig() {
        assertThrows(ServletException.class, () -> cacheControlFilter.init(null));
    }
}
