// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

@SpringBootTest
public class DefaultDmnEngineConfiguration_getDefaultInputEntryExpressionLanguage_66da4e24e3_Test {

    @MockBean
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setup() {
        Mockito.when(defaultDmnEngineConfiguration.getDefaultInputEntryExpressionLanguage())
                .thenReturn("ExpectedLanguage");
    }

    @Test
    public void testGetDefaultInputEntryExpressionLanguage_Success() {
        String result = defaultDmnEngineConfiguration.getDefaultInputEntryExpressionLanguage();
        Assertions.assertEquals("ExpectedLanguage", result);
    }

    @Test
    public void testGetDefaultInputEntryExpressionLanguage_Failure() {
        Mockito.when(defaultDmnEngineConfiguration.getDefaultInputEntryExpressionLanguage())
                .thenReturn("UnexpectedLanguage");
        String result = defaultDmnEngineConfiguration.getDefaultInputEntryExpressionLanguage();
        Assertions.assertNotEquals("ExpectedLanguage", result);
    }
}
