// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.feel.impl.FeelEngine;
import org.camunda.bpm.dmn.feel.impl.FeelEngineFactory;
import org.camunda.bpm.dmn.feel.impl.juel.FeelEngineFactoryImpl;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

public class DefaultDmnEngineConfiguration_setFeelEngineFactory_8e16b1e58e_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private FeelEngineFactory feelEngineFactory;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        feelEngineFactory = new FeelEngineFactoryImpl();
    }

    @Test
    public void testSetFeelEngineFactory() {
        defaultDmnEngineConfiguration.setFeelEngineFactory(feelEngineFactory);
        assertEquals(feelEngineFactory, defaultDmnEngineConfiguration.getFeelEngineFactory());
    }

    @Test
    public void testSetFeelEngineFactory_ClearCachedFeelEngine() {
        defaultDmnEngineConfiguration.setFeelEngineFactory(feelEngineFactory);
        FeelEngine cachedFeelEngine = defaultDmnEngineConfiguration.getFeelEngine();
        defaultDmnEngineConfiguration.setFeelEngineFactory(feelEngineFactory);
        assertNull(defaultDmnEngineConfiguration.getFeelEngine());
    }
}
