// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.impl.metrics.DmnEngineMetricCollector;
import org.camunda.bpm.dmn.engine.impl.metrics.DmnEngineMetricCollectorWrapper;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
@SpringBootTest
public class DefaultDmnEngineConfiguration_getEngineMetricCollector_47302e6d2e_Test {

    @Mock
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    private DmnEngineMetricCollectorWrapper engineMetricCollectorWrapper;

    @Before
    public void setUp() {
        when(defaultDmnEngineConfiguration.getEngineMetricCollector()).thenReturn(engineMetricCollectorWrapper);
    }

    @Test
    public void testGetEngineMetricCollectorSuccess() {
        DmnEngineMetricCollector result = defaultDmnEngineConfiguration.getEngineMetricCollector();
        assertEquals(engineMetricCollectorWrapper, result);
    }

    @Test(expected = NullPointerException.class)
    public void testGetEngineMetricCollectorFailure() {
        when(defaultDmnEngineConfiguration.getEngineMetricCollector()).thenThrow(NullPointerException.class);
        defaultDmnEngineConfiguration.getEngineMetricCollector();
    }
}
