// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.camunda.bpm.dmn.engine.delegate.DmnDecisionTableEvaluationListener;

import java.util.ArrayList;
import java.util.List;

public class DefaultDmnEngineConfiguration_getCustomPreDecisionTableEvaluationListeners_86e1ab94b4_Test {

    @InjectMocks
    DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    List<DmnDecisionTableEvaluationListener> customPreDecisionTableEvaluationListeners;

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        customPreDecisionTableEvaluationListeners = new ArrayList<>();
    }

    @Test
    public void testGetCustomPreDecisionTableEvaluationListeners_Success() {
        List<DmnDecisionTableEvaluationListener> result = defaultDmnEngineConfiguration.getCustomPreDecisionTableEvaluationListeners();
        Assert.assertEquals(customPreDecisionTableEvaluationListeners, result);
    }

    @Test
    public void testGetCustomPreDecisionTableEvaluationListeners_Failure() {
        List<DmnDecisionTableEvaluationListener> result = defaultDmnEngineConfiguration.getCustomPreDecisionTableEvaluationListeners();
        Assert.assertNotEquals(new ArrayList<>(), result);
    }
}
