// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class DefaultDmnEngineConfiguration_setDefaultOutputEntryExpressionLanguage_b8ec833183_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testSetDefaultOutputEntryExpressionLanguage() {
        String expressionLanguage = "Java";
        defaultDmnEngineConfiguration.setDefaultOutputEntryExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, defaultDmnEngineConfiguration.getDefaultOutputEntryExpressionLanguage());
    }

    @Test
    public void testSetDefaultOutputEntryExpressionLanguage_EmptyString() {
        String expressionLanguage = "";
        defaultDmnEngineConfiguration.setDefaultOutputEntryExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, defaultDmnEngineConfiguration.getDefaultOutputEntryExpressionLanguage());
    }
}
