// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class DefaultDmnEngineConfiguration_getDefaultInputExpressionExpressionLanguage_a0828f9c42_Test {

    @InjectMocks
    DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        defaultDmnEngineConfiguration.setDefaultInputExpressionExpressionLanguage("Java");
    }

    @Test
    public void testGetDefaultInputExpressionExpressionLanguage_Success() {
        String result = defaultDmnEngineConfiguration.getDefaultInputExpressionExpressionLanguage();
        assertEquals("Java", result, "The default Input Expression Expression Language should be Java");
    }

    @Test
    public void testGetDefaultInputExpressionExpressionLanguage_Failure() {
        String result = defaultDmnEngineConfiguration.getDefaultInputExpressionExpressionLanguage();
        assertEquals("Python", result, "The default Input Expression Expression Language should not be Python");
    }
}
