// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.camunda.bpm.dmn.engine.impl.spi.transform.DmnTransformer;
import org.camunda.bpm.dmn.engine.impl.DefaultDmnEngine;
import org.camunda.bpm.dmn.engine.impl.DefaultDmnEngineConfiguration;
import org.junit.Before;
import org.junit.Test;

public class DefaultDmnEngine_DefaultDmnEngine_dcf67d10d8_Test {

    private DefaultDmnEngineConfiguration dmnEngineConfiguration;
    private DmnTransformer transformer;
    private DefaultDmnEngine defaultDmnEngine;

    @Before
    public void setUp() {
        dmnEngineConfiguration = mock(DefaultDmnEngineConfiguration.class);
        transformer = mock(DmnTransformer.class);
        when(dmnEngineConfiguration.getTransformer()).thenReturn(transformer);
    }

    @Test
    public void testDefaultDmnEngineConstructor() {
        defaultDmnEngine = new DefaultDmnEngine(dmnEngineConfiguration);
        assertEquals(dmnEngineConfiguration, defaultDmnEngine.getDmnEngineConfiguration());
        assertEquals(transformer, defaultDmnEngine.getTransformer());
    }

    @Test(expected = NullPointerException.class)
    public void testDefaultDmnEngineConstructorWithNullConfiguration() {
        defaultDmnEngine = new DefaultDmnEngine(null);
    }
}
