// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;
import static org.mockito.Mockito.mock;

import org.camunda.bpm.dmn.engine.DmnEngineConfiguration;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class DefaultDmnEngine_getConfiguration_0300abcca9_Test {

    @Mock
    private DmnEngineConfiguration dmnEngineConfiguration;

    private DefaultDmnEngine defaultDmnEngine;

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        defaultDmnEngine = new DefaultDmnEngine(dmnEngineConfiguration);
    }

    @Test
    public void testGetConfiguration() {
        DmnEngineConfiguration config = mock(DmnEngineConfiguration.class);
        when(dmnEngineConfiguration.getConfiguration()).thenReturn(config);

        DmnEngineConfiguration result = defaultDmnEngine.getConfiguration();
        assertEquals(config, result);
    }

    @Test(expected = RuntimeException.class)
    public void testGetConfigurationWhenExceptionThrown() {
        when(dmnEngineConfiguration.getConfiguration()).thenThrow(RuntimeException.class);

        defaultDmnEngine.getConfiguration();
    }
}
