// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import static org.junit.Assert.assertEquals;

@RunWith(SpringRunner.class)
@SpringBootTest
public class DefaultDmnEngineConfiguration_defaultOutputEntryExpressionLanguage_924b8cebfc_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testDefaultOutputEntryExpressionLanguage_Success() {
        String expressionLanguage = "groovy";
        defaultDmnEngineConfiguration.defaultOutputEntryExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, defaultDmnEngineConfiguration.getDefaultOutputEntryExpressionLanguage());
    }

    @Test
    public void testDefaultOutputEntryExpressionLanguage_Null() {
        String expressionLanguage = null;
        defaultDmnEngineConfiguration.defaultOutputEntryExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, defaultDmnEngineConfiguration.getDefaultOutputEntryExpressionLanguage());
    }
}
