// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class DefaultDmnEngineConfiguration_setDefaultLiteralExpressionLanguage_a657e3d7ba_Test {
    
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setup() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testSetDefaultLiteralExpressionLanguage_ValidInput() {
        String expressionLanguage = "FEEL";
        defaultDmnEngineConfiguration.setDefaultLiteralExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, defaultDmnEngineConfiguration.getDefaultLiteralExpressionLanguage());
    }

    @Test
    public void testSetDefaultLiteralExpressionLanguage_NullInput() {
        String expressionLanguage = null;
        defaultDmnEngineConfiguration.setDefaultLiteralExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, defaultDmnEngineConfiguration.getDefaultLiteralExpressionLanguage());
    }

    @Test
    public void testSetDefaultLiteralExpressionLanguage_EmptyString() {
        String expressionLanguage = "";
        defaultDmnEngineConfiguration.setDefaultLiteralExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, defaultDmnEngineConfiguration.getDefaultLiteralExpressionLanguage());
    }
}
