// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.mockito.Mockito.*;

public class DefaultDmnEngineConfiguration_init_0ef02243a9_Test {

    @InjectMocks
    DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    DmnEngineMetricCollector dmnEngineMetricCollector;

    @Mock
    DmnDecisionTableEvaluationListener dmnDecisionTableEvaluationListener;

    @Mock
    DmnDecisionEvaluationListener dmnDecisionEvaluationListener;

    @Mock
    DmnScriptEngineResolver dmnScriptEngineResolver;

    @Mock
    ElProvider elProvider;

    @Mock
    FeelEngine feelEngine;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testInit_SuccessScenario() {
        defaultDmnEngineConfiguration.init();
        verify(defaultDmnEngineConfiguration, times(1)).initMetricCollector();
        verify(defaultDmnEngineConfiguration, times(1)).initDecisionTableEvaluationListener();
        verify(defaultDmnEngineConfiguration, times(1)).initDecisionEvaluationListener();
        verify(defaultDmnEngineConfiguration, times(1)).initScriptEngineResolver();
        verify(defaultDmnEngineConfiguration, times(1)).initElDefaults();
        verify(defaultDmnEngineConfiguration, times(1)).initElProvider();
        verify(defaultDmnEngineConfiguration, times(1)).initFeelEngine();
    }

    @Test
    public void testInit_FailureScenario() {
        doThrow(new RuntimeException()).when(defaultDmnEngineConfiguration).initMetricCollector();
        assertThrows(RuntimeException.class, () -> defaultDmnEngineConfiguration.init());
    }
}
