// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.delegate.DmnDecisionTableEvaluationListener;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class DefaultDmnEngineConfiguration_setCustomPreDecisionTableEvaluationListeners_78a29ba868_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    private DmnDecisionTableEvaluationListener listener1;

    @Mock
    private DmnDecisionTableEvaluationListener listener2;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testSetCustomPreDecisionTableEvaluationListeners() {
        List<DmnDecisionTableEvaluationListener> listeners = Arrays.asList(listener1, listener2);
        defaultDmnEngineConfiguration.setCustomPreDecisionTableEvaluationListeners(listeners);
        assertEquals(listeners, defaultDmnEngineConfiguration.getCustomPreDecisionTableEvaluationListeners());
    }

    @Test
    public void testSetCustomPreDecisionTableEvaluationListeners_Null() {
        defaultDmnEngineConfiguration.setCustomPreDecisionTableEvaluationListeners(null);
        assertEquals(null, defaultDmnEngineConfiguration.getCustomPreDecisionTableEvaluationListeners());
    }
}
