// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class DefaultDmnEngineConfiguration_buildEngine_d7433ed72d_Test {

    @InjectMocks
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    private DmnEngine dmnEngine;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        when(defaultDmnEngineConfiguration.buildEngine()).thenReturn(dmnEngine);
    }

    @Test
    public void testBuildEngineSuccess() {
        DmnEngine result = defaultDmnEngineConfiguration.buildEngine();
        assertNotNull(result);
        assertEquals(dmnEngine, result);
    }

    @Test
    public void testBuildEngineFailure() {
        when(defaultDmnEngineConfiguration.buildEngine()).thenThrow(new RuntimeException());
        assertThrows(RuntimeException.class, () -> defaultDmnEngineConfiguration.buildEngine());
    }
}
