// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.impl.metrics.DefaultEngineMetricCollector;
import org.camunda.bpm.dmn.engine.spi.DmnEngineMetricCollector;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class DefaultDmnEngineConfiguration_initMetricCollector_4b9982633b_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private DmnEngineMetricCollector engineMetricCollector;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        engineMetricCollector = Mockito.mock(DmnEngineMetricCollector.class);
    }

    @Test
    public void testInitMetricCollector_WhenEngineMetricCollectorIsNull() {
        defaultDmnEngineConfiguration.initMetricCollector();
        assertNotNull(defaultDmnEngineConfiguration.getEngineMetricCollector());
        assertTrue(defaultDmnEngineConfiguration.getEngineMetricCollector() instanceof DefaultEngineMetricCollector);
    }

    @Test
    public void testInitMetricCollector_WhenEngineMetricCollectorIsNotNull() {
        defaultDmnEngineConfiguration.setEngineMetricCollector(engineMetricCollector);
        defaultDmnEngineConfiguration.initMetricCollector();
        assertSame(engineMetricCollector, defaultDmnEngineConfiguration.getEngineMetricCollector());
    }
}
