// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;
import static org.mockito.Mockito.mock;

import org.camunda.bpm.dmn.engine.DmnEngine;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class DefaultDmnEngineConfiguration_buildEngine_d7433ed72d_Test {

    @Mock
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testBuildEngine_Success() {
        try {
            DmnEngine engine = defaultDmnEngineConfiguration.buildEngine();
            assertNotNull(engine);
            assertTrue(engine instanceof DefaultDmnEngine);
        } catch (Exception e) {
            fail("Exception should not have been thrown.");
        }
    }

    @Test
    public void testBuildEngine_Exception() {
        try {
            Mockito.when(defaultDmnEngineConfiguration.buildEngine()).thenThrow(new RuntimeException());
            defaultDmnEngineConfiguration.buildEngine();
            fail("Exception should have been thrown.");
        } catch (Exception e) {
            assertTrue(e instanceof RuntimeException);
        }
    }
}
