// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.delegate.DmnDecisionTableEvaluationListener;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

@RunWith(SpringRunner.class)
@SpringBootTest
public class DefaultDmnEngineConfiguration_setCustomPostDecisionTableEvaluationListeners_bd4bd8da91_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testSetCustomPostDecisionTableEvaluationListeners() {
        List<DmnDecisionTableEvaluationListener> decisionTableEvaluationListeners = new ArrayList<>();
        DmnDecisionTableEvaluationListener listener = (decisionTable, variables, result) -> {};
        decisionTableEvaluationListeners.add(listener);

        defaultDmnEngineConfiguration.setCustomPostDecisionTableEvaluationListeners(decisionTableEvaluationListeners);

        assertEquals(decisionTableEvaluationListeners, defaultDmnEngineConfiguration.getCustomPostDecisionTableEvaluationListeners());
    }

    @Test
    public void testSetCustomPostDecisionTableEvaluationListeners_Null() {
        defaultDmnEngineConfiguration.setCustomPostDecisionTableEvaluationListeners(null);

        assertNull(defaultDmnEngineConfiguration.getCustomPostDecisionTableEvaluationListeners());
    }
}
