// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import java.util.ArrayList;
import java.util.List;
import org.camunda.bpm.dmn.engine.delegate.DmnDecisionTableEvaluationListener;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class DefaultDmnEngineConfiguration_setCustomPreDecisionTableEvaluationListeners_78a29ba868_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    private DmnDecisionTableEvaluationListener mockListener1;
    
    @Mock
    private DmnDecisionTableEvaluationListener mockListener2;

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testSetCustomPreDecisionTableEvaluationListeners() {
        List<DmnDecisionTableEvaluationListener> decisionTableEvaluationListeners = new ArrayList<>();
        decisionTableEvaluationListeners.add(mockListener1);
        decisionTableEvaluationListeners.add(mockListener2);

        defaultDmnEngineConfiguration.setCustomPreDecisionTableEvaluationListeners(decisionTableEvaluationListeners);

        assertEquals(decisionTableEvaluationListeners, defaultDmnEngineConfiguration.getCustomPreDecisionTableEvaluationListeners());
    }

    @Test
    public void testSetCustomPreDecisionTableEvaluationListenersWithNull() {
        defaultDmnEngineConfiguration.setCustomPreDecisionTableEvaluationListeners(null);

        assertNull(defaultDmnEngineConfiguration.getCustomPreDecisionTableEvaluationListeners());
    }
}
