// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import java.util.ArrayList;
import java.util.List;
import org.camunda.bpm.dmn.engine.delegate.DmnDecisionTableEvaluationListener;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class DefaultDmnEngineConfiguration_getCustomPreDecisionTableEvaluationListeners_86e1ab94b4_Test {

    @InjectMocks
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    private List<DmnDecisionTableEvaluationListener> customPreDecisionTableEvaluationListeners;

    @Before
    public void setUp() {
        when(defaultDmnEngineConfiguration.getCustomPreDecisionTableEvaluationListeners()).thenReturn(customPreDecisionTableEvaluationListeners);
    }

    @Test
    public void testGetCustomPreDecisionTableEvaluationListeners_Success() {
        List<DmnDecisionTableEvaluationListener> result = defaultDmnEngineConfiguration.getCustomPreDecisionTableEvaluationListeners();
        assertEquals(customPreDecisionTableEvaluationListeners, result);
    }

    @Test(expected = RuntimeException.class)
    public void testGetCustomPreDecisionTableEvaluationListeners_Failure() {
        when(defaultDmnEngineConfiguration.getCustomPreDecisionTableEvaluationListeners()).thenThrow(RuntimeException.class);
        defaultDmnEngineConfiguration.getCustomPreDecisionTableEvaluationListeners();
    }
}
