// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;
import org.camunda.bpm.dmn.engine.impl.spi.transform.DmnTransformer;
import org.mockito.Mock;
import static org.mockito.Mockito.*;
import static org.junit.Assert.*;

@RunWith(MockitoJUnitRunner.class)
public class DefaultDmnEngineConfiguration_transformer_15e3000c13_Test {

    @Mock
    private DmnTransformer mockTransformer;

    @Test
    public void testTransformer_Success() {
        DefaultDmnEngineConfiguration config = new DefaultDmnEngineConfiguration();
        DefaultDmnEngineConfiguration returnedConfig = config.transformer(mockTransformer);
        
        assertEquals(config, returnedConfig);
        verify(config, times(1)).setTransformer(mockTransformer);
    }

    @Test
    public void testTransformer_NullTransformer() {
        DefaultDmnEngineConfiguration config = new DefaultDmnEngineConfiguration();

        try {
            config.transformer(null);
            fail("Expected IllegalArgumentException");
        } catch (IllegalArgumentException e) {
            // Expected exception
        }
    }
}
