// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.DmnEngineConfiguration;
import org.camunda.bpm.dmn.engine.delegate.DmnDecisionEvaluationListener;
import org.camunda.bpm.dmn.engine.impl.metrics.DmnEngineMetricCollectorWrapper;
import org.camunda.bpm.dmn.engine.spi.DmnEngineMetricCollector;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.util.Collection;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class DefaultDmnEngineConfiguration_getDefaultDmnDecisionEvaluationListeners_797fa63b80_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private DmnEngineMetricCollector engineMetricCollector;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        engineMetricCollector = Mockito.mock(DmnEngineMetricCollector.class);
    }

    @Test
    public void testGetDefaultDmnDecisionEvaluationListeners_EngineMetricCollectorIsListener() {
        DmnDecisionEvaluationListener listener = Mockito.mock(DmnDecisionEvaluationListener.class);
        defaultDmnEngineConfiguration.setEngineMetricCollector((DmnEngineMetricCollector) listener);

        Collection<? extends DmnDecisionEvaluationListener> result = defaultDmnEngineConfiguration.getDefaultDmnDecisionEvaluationListeners();

        assertEquals(1, result.size());
        assertTrue(result.contains(listener));
    }

    @Test
    public void testGetDefaultDmnDecisionEvaluationListeners_EngineMetricCollectorIsNotListener() {
        defaultDmnEngineConfiguration.setEngineMetricCollector(engineMetricCollector);

        Collection<? extends DmnDecisionEvaluationListener> result = defaultDmnEngineConfiguration.getDefaultDmnDecisionEvaluationListeners();

        assertEquals(1, result.size());
        assertTrue(result.iterator().next() instanceof DmnEngineMetricCollectorWrapper);
    }
}
