// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.camunda.bpm.dmn.engine.delegate.DmnDecisionEvaluationListener;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.when;

public class DefaultDmnEngineConfiguration_customPostDecisionEvaluationListeners_3fdc63d3c6_Test {

    @Mock
    private DmnDecisionEvaluationListener listener1, listener2;

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testCustomPostDecisionEvaluationListeners() {
        List<DmnDecisionEvaluationListener> decisionEvaluationListeners = Arrays.asList(listener1, listener2);
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.customPostDecisionEvaluationListeners(decisionEvaluationListeners);

        assertEquals(result, defaultDmnEngineConfiguration);
        assertEquals(decisionEvaluationListeners, defaultDmnEngineConfiguration.getCustomPostDecisionEvaluationListeners());
    }

    @Test
    public void testCustomPostDecisionEvaluationListeners_NullList() {
        assertThrows(NullPointerException.class, () -> {
            defaultDmnEngineConfiguration.customPostDecisionEvaluationListeners(null);
        });
    }
}
