// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import static org.junit.Assert.*;

@RunWith(SpringRunner.class)
@SpringBootTest
public class DefaultDmnEngineConfiguration_isEnableFeelLegacyBehavior_28ac6618f5_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testIsEnableFeelLegacyBehavior_True() {
        defaultDmnEngineConfiguration.setEnableFeelLegacyBehavior(true);
        boolean result = defaultDmnEngineConfiguration.isEnableFeelLegacyBehavior();
        assertTrue(result);
    }

    @Test
    public void testIsEnableFeelLegacyBehavior_False() {
        defaultDmnEngineConfiguration.setEnableFeelLegacyBehavior(false);
        boolean result = defaultDmnEngineConfiguration.isEnableFeelLegacyBehavior();
        assertFalse(result);
    }
}
