// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.delegate.DmnDecisionEvaluationListener;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class DefaultDmnEngineConfiguration_setCustomPreDecisionEvaluationListeners_84f7ff42b8_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testSetCustomPreDecisionEvaluationListeners() {
        List<DmnDecisionEvaluationListener> decisionEvaluationListeners = new ArrayList<>();
        decisionEvaluationListeners.add(new DmnDecisionEvaluationListener() {
            @Override
            public void notify(DmnDecisionTableEvaluationEvent event) {
                // Add implementation
            }
        });
        decisionEvaluationListeners.add(new DmnDecisionEvaluationListener() {
            @Override
            public void notify(DmnDecisionTableEvaluationEvent event) {
                // Add implementation
            }
        });

        defaultDmnEngineConfiguration.setCustomPreDecisionEvaluationListeners(decisionEvaluationListeners);

        assertEquals(decisionEvaluationListeners, defaultDmnEngineConfiguration.getCustomPreDecisionEvaluationListeners());
    }

    @Test
    public void testSetCustomPreDecisionEvaluationListenersWithNull() {
        defaultDmnEngineConfiguration.setCustomPreDecisionEvaluationListeners(null);

        assertNull(defaultDmnEngineConfiguration.getCustomPreDecisionEvaluationListeners());
    }
}
