// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.camunda.bpm.dmn.engine.delegate.DmnDecisionTableEvaluationListener;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class DefaultDmnEngineConfiguration_initDecisionTableEvaluationListener_33f1930d52_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testInitDecisionTableEvaluationListener_BothListsAreNull() {
        defaultDmnEngineConfiguration.initDecisionTableEvaluationListener();
        assertNull(defaultDmnEngineConfiguration.getDecisionTableEvaluationListeners());
    }

    @Test
    public void testInitDecisionTableEvaluationListener_BothListsAreNotEmpty() {
        List<DmnDecisionTableEvaluationListener> preListeners = new ArrayList<>();
        preListeners.add(Mockito.mock(DmnDecisionTableEvaluationListener.class));
        List<DmnDecisionTableEvaluationListener> postListeners = new ArrayList<>();
        postListeners.add(Mockito.mock(DmnDecisionTableEvaluationListener.class));

        defaultDmnEngineConfiguration.setCustomPreDecisionTableEvaluationListeners(preListeners);
        defaultDmnEngineConfiguration.setCustomPostDecisionTableEvaluationListeners(postListeners);
        defaultDmnEngineConfiguration.initDecisionTableEvaluationListener();

        assertEquals(2, defaultDmnEngineConfiguration.getDecisionTableEvaluationListeners().size());
    }

    @Test
    public void testInitDecisionTableEvaluationListener_OneListIsEmpty() {
        List<DmnDecisionTableEvaluationListener> preListeners = new ArrayList<>();
        preListeners.add(Mockito.mock(DmnDecisionTableEvaluationListener.class));

        defaultDmnEngineConfiguration.setCustomPreDecisionTableEvaluationListeners(preListeners);
        defaultDmnEngineConfiguration.initDecisionTableEvaluationListener();

        assertEquals(1, defaultDmnEngineConfiguration.getDecisionTableEvaluationListeners().size());
    }
}
