// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;
import org.camunda.bpm.dmn.engine.delegate.DmnDecisionTableEvaluationListener;

import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertEquals;

public class DefaultDmnEngineConfiguration_setCustomPreDecisionTableEvaluationListeners_78a29ba868_Test {

  private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
  private DmnDecisionTableEvaluationListener mockListener1;
  private DmnDecisionTableEvaluationListener mockListener2;

  @Before
  public void setUp() {
    defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    mockListener1 = Mockito.mock(DmnDecisionTableEvaluationListener.class);
    mockListener2 = Mockito.mock(DmnDecisionTableEvaluationListener.class);
  }

  @Test
  public void testSetCustomPreDecisionTableEvaluationListeners() {
    List<DmnDecisionTableEvaluationListener> testListeners = Arrays.asList(mockListener1, mockListener2);
    defaultDmnEngineConfiguration.setCustomPreDecisionTableEvaluationListeners(testListeners);
    assertEquals(testListeners, defaultDmnEngineConfiguration.getCustomPreDecisionTableEvaluationListeners());
  }

  @Test(expected = NullPointerException.class)
  public void testSetCustomPreDecisionTableEvaluationListenersWithNull() {
    defaultDmnEngineConfiguration.setCustomPreDecisionTableEvaluationListeners(null);
  }

}
