// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThrows;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.Arrays;
import java.util.List;

import org.camunda.bpm.dmn.engine.DmnDecision;
import org.camunda.bpm.dmn.engine.DmnDecisionResult;
import org.camunda.bpm.engine.variable.context.VariableContext;
import org.camunda.bpm.model.dmn.DmnModelInstance;
import org.junit.Before;
import org.junit.Test;

public class DefaultDmnEngine_evaluateDecision_d40b139e89_Test {

    private DefaultDmnEngine defaultDmnEngine;
    private DmnModelInstance dmnModelInstance;
    private VariableContext variableContext;

    @Before
    public void setUp() {
        defaultDmnEngine = new DefaultDmnEngine();
        dmnModelInstance = mock(DmnModelInstance.class);
        variableContext = mock(VariableContext.class);
    }

    @Test
    public void testEvaluateDecision_Success() {
        String decisionKey = "testKey";
        DmnDecision decision = mock(DmnDecision.class);
        DmnDecisionResult decisionResult = mock(DmnDecisionResult.class);

        when(decision.getKey()).thenReturn(decisionKey);
        when(defaultDmnEngine.evaluateDecision(decision, variableContext)).thenReturn(decisionResult);

        List<DmnDecision> decisions = Arrays.asList(decision);
        when(defaultDmnEngine.parseDecisions(dmnModelInstance)).thenReturn(decisions);

        DmnDecisionResult result = defaultDmnEngine.evaluateDecision(decisionKey, dmnModelInstance, variableContext);
        assertEquals(decisionResult, result);
    }

    @Test
    public void testEvaluateDecision_Failure() {
        String decisionKey = "testKey";
        DmnDecision decision = mock(DmnDecision.class);

        when(decision.getKey()).thenReturn("wrongKey");

        List<DmnDecision> decisions = Arrays.asList(decision);
        when(defaultDmnEngine.parseDecisions(dmnModelInstance)).thenReturn(decisions);

        Exception exception = assertThrows(RuntimeException.class, () -> {
            defaultDmnEngine.evaluateDecision(decisionKey, dmnModelInstance, variableContext);
        });

        String expectedMessage = "Unable to find decision with key " + decisionKey;
        String actualMessage = exception.getMessage();

        assertEquals(expectedMessage, actualMessage);
    }
}
