// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.DmnDecisionLogic;
import org.camunda.bpm.dmn.engine.impl.evaluation.DecisionLiteralExpressionEvaluationHandler;
import org.camunda.bpm.dmn.engine.impl.evaluation.DecisionTableEvaluationHandler;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

@RunWith(MockitoJUnitRunner.class)
public class DefaultDmnDecisionContext_DefaultDmnDecisionContext_cd6e5a4093_Test {

    @Mock
    private DefaultDmnEngineConfiguration configuration;

    private DefaultDmnDecisionContext decisionContext;

    @Before
    public void setup() {
        when(configuration.getDecisionEvaluationListeners()).thenReturn(new ArrayList<>());
        decisionContext = new DefaultDmnDecisionContext(configuration);
    }

    @Test
    public void testDefaultDmnDecisionContext() {
        assertNotNull(decisionContext);
        assertTrue(decisionContext.getEvaluationListeners().isEmpty());

        Map<Class<? extends DmnDecisionLogic>, DmnDecisionLogicEvaluationHandler> evaluationHandlers = decisionContext.getEvaluationHandlers();
        assertNotNull(evaluationHandlers);
        assertEquals(2, evaluationHandlers.size());
        assertTrue(evaluationHandlers.get(DmnDecisionTableImpl.class) instanceof DecisionTableEvaluationHandler);
        assertTrue(evaluationHandlers.get(DmnDecisionLiteralExpressionImpl.class) instanceof DecisionLiteralExpressionEvaluationHandler);
    }

    @Test(expected = NullPointerException.class)
    public void testDefaultDmnDecisionContextWithNullConfiguration() {
        new DefaultDmnDecisionContext(null);
    }
}
