// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import java.util.ArrayList;
import java.util.List;
import org.camunda.bpm.dmn.engine.delegate.DmnDecisionTableEvaluationListener;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class DefaultDmnEngineConfiguration_customPostDecisionTableEvaluationListeners_668f82d3fb_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private List<DmnDecisionTableEvaluationListener> decisionTableEvaluationListeners;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        decisionTableEvaluationListeners = new ArrayList<>();
        decisionTableEvaluationListeners.add(mock(DmnDecisionTableEvaluationListener.class));
    }

    @Test
    public void testCustomPostDecisionTableEvaluationListeners_Success() {
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.customPostDecisionTableEvaluationListeners(decisionTableEvaluationListeners);
        assertEquals(defaultDmnEngineConfiguration, result, "The returned object should be the same as the original object");
        assertEquals(decisionTableEvaluationListeners, defaultDmnEngineConfiguration.getCustomPostDecisionTableEvaluationListeners(), "The listeners should be the same as the ones set");
    }

    @Test
    public void testCustomPostDecisionTableEvaluationListeners_NullInput() {
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.customPostDecisionTableEvaluationListeners(null);
        assertEquals(defaultDmnEngineConfiguration, result, "The returned object should be the same as the original object");
        assertEquals(null, defaultDmnEngineConfiguration.getCustomPostDecisionTableEvaluationListeners(), "The listeners should be null");
    }
}
