// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class DefaultDmnEngineConfiguration_getTransformer_9caaa9c930_Test {

    @Mock
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    private DmnTransformer mockTransformer;

    @Before
    public void setUp() {
        when(defaultDmnEngineConfiguration.getTransformer()).thenReturn(mockTransformer);
    }

    @Test
    public void testGetTransformer() {
        DmnTransformer transformer = defaultDmnEngineConfiguration.getTransformer();
        assertEquals(mockTransformer, transformer);
    }

    @Test(expected = NullPointerException.class)
    public void testGetTransformer_whenTransformerIsNull() {
        when(defaultDmnEngineConfiguration.getTransformer()).thenReturn(null);
        defaultDmnEngineConfiguration.getTransformer();
    }
}
