// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.impl.spi.el.ElProvider;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class DefaultDmnEngineConfiguration_setElProvider_b7b4b33d7f_Test {
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private ElProvider elProvider;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        elProvider = Mockito.mock(ElProvider.class);
    }

    @Test
    public void testSetElProvider() {
        defaultDmnEngineConfiguration.setElProvider(elProvider);
        assertEquals(elProvider, defaultDmnEngineConfiguration.getElProvider());
    }

    @Test
    public void testSetElProvider_null() {
        defaultDmnEngineConfiguration.setElProvider(null);
        assertNull(defaultDmnEngineConfiguration.getElProvider());
    }
}
