// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import java.util.Arrays;
import java.util.List;
import org.camunda.bpm.dmn.feel.impl.scala.function.FeelCustomFunctionProvider;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class DefaultDmnEngineConfiguration_setFeelCustomFunctionProviders_e1e5ee9fa0_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    private FeelCustomFunctionProvider feelCustomFunctionProvider1;

    @Mock
    private FeelCustomFunctionProvider feelCustomFunctionProvider2;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testSetFeelCustomFunctionProviders() {
        List<FeelCustomFunctionProvider> providers = Arrays.asList(feelCustomFunctionProvider1, feelCustomFunctionProvider2);
        defaultDmnEngineConfiguration.setFeelCustomFunctionProviders(providers);
        assertEquals(providers, defaultDmnEngineConfiguration.getFeelCustomFunctionProviders());
    }

    @Test(expected = NullPointerException.class)
    public void testSetFeelCustomFunctionProviders_Null() {
        defaultDmnEngineConfiguration.setFeelCustomFunctionProviders(null);
    }
}
