// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;

import org.camunda.bpm.dmn.engine.impl.metrics.DmnEngineMetricCollectorWrapper;
import org.camunda.bpm.dmn.engine.spi.DmnEngineMetricCollector;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class DefaultDmnEngineConfiguration_setEngineMetricCollector_21748071e3_Test {

  private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
  private DmnEngineMetricCollector dmnEngineMetricCollector;

  @BeforeEach
  public void setUp() {
    defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    dmnEngineMetricCollector = mock(DmnEngineMetricCollectorWrapper.class);
  }

  @Test
  public void testSetEngineMetricCollector() {
    defaultDmnEngineConfiguration.setEngineMetricCollector(dmnEngineMetricCollector);
    assertEquals(dmnEngineMetricCollector, defaultDmnEngineConfiguration.getEngineMetricCollector());
  }

  @Test
  public void testSetEngineMetricCollectorWithNull() {
    defaultDmnEngineConfiguration.setEngineMetricCollector(null);
    assertEquals(null, defaultDmnEngineConfiguration.getEngineMetricCollector());
  }
}
