// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.impl.spi.el.ElProvider;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class DefaultDmnEngineConfiguration_elProvider_091a424170_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    private ElProvider elProvider;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testElProviderSuccess() {
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.elProvider(elProvider);
        assertSame(defaultDmnEngineConfiguration, result);
        verify(defaultDmnEngineConfiguration, times(1)).setElProvider(elProvider);
    }

    @Test
    public void testElProviderNull() {
        assertThrows(NullPointerException.class, () -> {
            defaultDmnEngineConfiguration.elProvider(null);
        });
    }
}
