// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.delegate.DmnDecisionEvaluationListener;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class DefaultDmnEngineConfiguration_getDecisionEvaluationListeners_bf1dd2cbe1_Test {

    @InjectMocks
    DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    List<DmnDecisionEvaluationListener> decisionEvaluationListeners;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetDecisionEvaluationListeners_Success() {
        List<DmnDecisionEvaluationListener> expectedListeners = new ArrayList<>();
        when(decisionEvaluationListeners.size()).thenReturn(2);
        when(defaultDmnEngineConfiguration.getDecisionEvaluationListeners()).thenReturn(expectedListeners);

        List<DmnDecisionEvaluationListener> actualListeners = defaultDmnEngineConfiguration.getDecisionEvaluationListeners();

        assertEquals(expectedListeners, actualListeners);
        assertEquals(2, actualListeners.size());
    }

    @Test
    public void testGetDecisionEvaluationListeners_EmptyList() {
        List<DmnDecisionEvaluationListener> expectedListeners = new ArrayList<>();
        when(decisionEvaluationListeners.size()).thenReturn(0);
        when(defaultDmnEngineConfiguration.getDecisionEvaluationListeners()).thenReturn(expectedListeners);

        List<DmnDecisionEvaluationListener> actualListeners = defaultDmnEngineConfiguration.getDecisionEvaluationListeners();

        assertEquals(expectedListeners, actualListeners);
        assertEquals(0, actualListeners.size());
    }
}
