// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

public class DefaultDmnEngineConfiguration_getDefaultLiteralExpressionLanguage_2d0f61b0cd_Test {

    @InjectMocks
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        defaultDmnEngineConfiguration.setDefaultLiteralExpressionLanguage("Java");
    }

    @Test
    public void testGetDefaultLiteralExpressionLanguage_Success() {
        String expected = "Java";
        String actual = defaultDmnEngineConfiguration.getDefaultLiteralExpressionLanguage();
        Assertions.assertEquals(expected, actual, "The expected and actual literal expression language should match");
    }

    @Test
    public void testGetDefaultLiteralExpressionLanguage_Failure() {
        String expected = "Python";
        String actual = defaultDmnEngineConfiguration.getDefaultLiteralExpressionLanguage();
        Assertions.assertNotEquals(expected, actual, "The expected and actual literal expression language should not match");
    }
}
