// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.camunda.bpm.dmn.engine.delegate.DmnDecisionTableEvaluationListener;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class DefaultDmnEngineConfiguration_setCustomPostDecisionTableEvaluationListeners_bd4bd8da91_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private DmnDecisionTableEvaluationListener mockListener1;
    private DmnDecisionTableEvaluationListener mockListener2;

    @BeforeEach
    public void setup() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        mockListener1 = Mockito.mock(DmnDecisionTableEvaluationListener.class);
        mockListener2 = Mockito.mock(DmnDecisionTableEvaluationListener.class);
    }

    @Test
    public void testSetCustomPostDecisionTableEvaluationListeners() {
        List<DmnDecisionTableEvaluationListener> decisionTableEvaluationListeners = Arrays.asList(mockListener1, mockListener2);
        defaultDmnEngineConfiguration.setCustomPostDecisionTableEvaluationListeners(decisionTableEvaluationListeners);

        assertEquals(decisionTableEvaluationListeners, defaultDmnEngineConfiguration.getCustomPostDecisionTableEvaluationListeners());
    }

    @Test
    public void testSetCustomPostDecisionTableEvaluationListenersWithEmptyList() {
        List<DmnDecisionTableEvaluationListener> decisionTableEvaluationListeners = Arrays.asList();
        defaultDmnEngineConfiguration.setCustomPostDecisionTableEvaluationListeners(decisionTableEvaluationListeners);

        assertEquals(decisionTableEvaluationListeners, defaultDmnEngineConfiguration.getCustomPostDecisionTableEvaluationListeners());
    }
}
