// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.feel.impl.scala.function.FeelCustomFunctionProvider;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import java.util.Arrays;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class DefaultDmnEngineConfiguration_setFeelCustomFunctionProviders_e1e5ee9fa0_Test {
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testSetFeelCustomFunctionProviders() {
        FeelCustomFunctionProvider mockProvider1 = Mockito.mock(FeelCustomFunctionProvider.class);
        FeelCustomFunctionProvider mockProvider2 = Mockito.mock(FeelCustomFunctionProvider.class);

        List<FeelCustomFunctionProvider> mockProviders = Arrays.asList(mockProvider1, mockProvider2);
        defaultDmnEngineConfiguration.setFeelCustomFunctionProviders(mockProviders);

        assertEquals(mockProviders, defaultDmnEngineConfiguration.getFeelCustomFunctionProviders());
    }

    @Test
    public void testSetFeelCustomFunctionProviders_Null() {
        assertThrows(NullPointerException.class, () -> {
            defaultDmnEngineConfiguration.setFeelCustomFunctionProviders(null);
        });
    }
}
