// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class DefaultDmnEngineConfiguration_setDefaultLiteralExpressionLanguage_a657e3d7ba_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testSetDefaultLiteralExpressionLanguage_validInput() {
        String expressionLanguage = "FEEL";
        defaultDmnEngineConfiguration.setDefaultLiteralExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, defaultDmnEngineConfiguration.getDefaultLiteralExpressionLanguage());
    }

    @Test
    public void testSetDefaultLiteralExpressionLanguage_nullInput() {
        defaultDmnEngineConfiguration.setDefaultLiteralExpressionLanguage(null);
        assertEquals(null, defaultDmnEngineConfiguration.getDefaultLiteralExpressionLanguage());
    }
}
