// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.util.Arrays;
import java.util.List;

import org.camunda.bpm.dmn.feel.impl.scala.function.FeelCustomFunctionProvider;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class DefaultDmnEngineConfiguration_feelCustomFunctionProviders_c023fb082e_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private FeelCustomFunctionProvider feelCustomFunctionProvider;

    @BeforeEach
    public void setup() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        feelCustomFunctionProvider = Mockito.mock(FeelCustomFunctionProvider.class);
    }

    @Test
    public void testFeelCustomFunctionProviders() {
        List<FeelCustomFunctionProvider> feelCustomFunctionProviders = Arrays.asList(feelCustomFunctionProvider);
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.feelCustomFunctionProviders(feelCustomFunctionProviders);
        assertEquals(defaultDmnEngineConfiguration, result);
    }

    @Test
    public void testFeelCustomFunctionProviders_NullList() {
        assertThrows(NullPointerException.class, () -> {
            defaultDmnEngineConfiguration.feelCustomFunctionProviders(null);
        });
    }
}
