// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class DefaultDmnEngineConfiguration_defaultLiteralExpressionLanguage_0a9bedd54d_Test {

    private DefaultDmnEngineConfiguration config;

    @BeforeEach
    public void setup() {
        config = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testDefaultLiteralExpressionLanguage_WithValidExpressionLanguage() {
        String expressionLanguage = "JUEL";
        config.defaultLiteralExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, config.getDefaultLiteralExpressionLanguage());
    }

    @Test
    public void testDefaultLiteralExpressionLanguage_WithEmptyExpressionLanguage() {
        String expressionLanguage = "";
        config.defaultLiteralExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, config.getDefaultLiteralExpressionLanguage());
    }

    @Test
    public void testDefaultLiteralExpressionLanguage_WithNullExpressionLanguage() {
        String expressionLanguage = null;
        config.defaultLiteralExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, config.getDefaultLiteralExpressionLanguage());
    }
}
