// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.camunda.bpm.dmn.engine.impl.el.DefaultScriptEngineResolver;
import static org.junit.jupiter.api.Assertions.*;

public class DefaultDmnEngineConfiguration_initScriptEngineResolver_3ea497e2ed_Test {
   
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setup() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testInitScriptEngineResolverWhenScriptEngineResolverIsNull() {
        defaultDmnEngineConfiguration.initScriptEngineResolver();
        assertNotNull(defaultDmnEngineConfiguration.getScriptEngineResolver());
        assertTrue(defaultDmnEngineConfiguration.getScriptEngineResolver() instanceof DefaultScriptEngineResolver);
    }

    @Test
    public void testInitScriptEngineResolverWhenScriptEngineResolverIsNotNull() {
        DefaultScriptEngineResolver scriptEngineResolver = new DefaultScriptEngineResolver();
        defaultDmnEngineConfiguration.setScriptEngineResolver(scriptEngineResolver);
        defaultDmnEngineConfiguration.initScriptEngineResolver();
        assertSame(scriptEngineResolver, defaultDmnEngineConfiguration.getScriptEngineResolver());
    }
}
