// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.feel.impl.FeelEngine;
import org.camunda.bpm.dmn.feel.impl.FeelEngineFactory;
import org.camunda.bpm.dmn.feel.impl.juel.FeelEngineFactoryImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class DefaultDmnEngineConfiguration_getFeelEngine_f6b657c84a_Test {

    @InjectMocks
    DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    FeelEngine feelEngine;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    void testGetFeelEngine_Success() {
        when(defaultDmnEngineConfiguration.getFeelEngine()).thenReturn(feelEngine);
        FeelEngine result = defaultDmnEngineConfiguration.getFeelEngine();
        assertEquals(feelEngine, result);
    }

    @Test
    void testGetFeelEngine_Null() {
        when(defaultDmnEngineConfiguration.getFeelEngine()).thenReturn(null);
        FeelEngine result = defaultDmnEngineConfiguration.getFeelEngine();
        assertNull(result);
    }
}
