// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.impl.metrics.DefaultEngineMetricCollector;
import org.camunda.bpm.dmn.engine.spi.DmnEngineMetricCollector;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class DefaultDmnEngineConfiguration_getEngineMetricCollector_47302e6d2e_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testGetEngineMetricCollector() {
        DmnEngineMetricCollector engineMetricCollector = new DefaultEngineMetricCollector();
        defaultDmnEngineConfiguration.setEngineMetricCollector(engineMetricCollector);

        DmnEngineMetricCollector actual = defaultDmnEngineConfiguration.getEngineMetricCollector();

        assertNotNull(actual, "EngineMetricCollector should not be null");
        assertEquals(engineMetricCollector, actual, "EngineMetricCollector returned is not as expected");
    }

    @Test
    public void testGetEngineMetricCollector_Null() {
        defaultDmnEngineConfiguration.setEngineMetricCollector(null);

        DmnEngineMetricCollector actual = defaultDmnEngineConfiguration.getEngineMetricCollector();

        assertNull(actual, "EngineMetricCollector should be null");
    }
}
