// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.camunda.bpm.dmn.engine.spi.DmnEngineMetricCollector;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.when;

public class DefaultDmnEngineConfiguration_engineMetricCollector_e1d90ecaa2_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private DmnEngineMetricCollector dmnEngineMetricCollector;

    @BeforeEach
    public void setup() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        dmnEngineMetricCollector = Mockito.mock(DmnEngineMetricCollector.class);
    }

    @Test
    public void testEngineMetricCollector_Success() {
        defaultDmnEngineConfiguration.engineMetricCollector(dmnEngineMetricCollector);
        assertEquals(dmnEngineMetricCollector, defaultDmnEngineConfiguration.getEngineMetricCollector());
    }

    @Test
    public void testEngineMetricCollector_Null() {
        assertThrows(NullPointerException.class, () -> defaultDmnEngineConfiguration.engineMetricCollector(null));
    }
}
