// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import static org.mockito.Mockito.*;
import org.mockito.junit.MockitoJUnitRunner;
import org.camunda.bpm.dmn.engine.DmnDecision;
import org.camunda.bpm.dmn.engine.DmnDecisionResult;
import org.camunda.bpm.engine.variable.context.VariableContext;
import org.camunda.bpm.engine.variable.Variables;

import static org.junit.Assert.*;

@RunWith(MockitoJUnitRunner.class)
public class DefaultDmnDecisionContext_evaluateDecision_69d4b7215f_Test {

  @InjectMocks
  private DefaultDmnDecisionContext defaultDmnDecisionContext;

  @Mock
  private DmnDecision decision;
  
  @Mock
  private VariableContext variableContext;

  @Test
  public void testEvaluateDecisionSuccess() {
    when(decision.getKey()).thenReturn("testKey");
    DmnDecisionResult result = defaultDmnDecisionContext.evaluateDecision(decision, variableContext);
    assertNotNull(result);
  }

  @Test(expected = RuntimeException.class)
  public void testEvaluateDecisionFailure() {
    when(decision.getKey()).thenReturn(null);
    defaultDmnDecisionContext.evaluateDecision(decision, variableContext);
  }
}
