// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.impl.spi.el.ElProvider;
import org.camunda.bpm.dmn.engine.impl.el.JuelElProvider;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class DefaultDmnEngineConfiguration_initElProvider_e7ed92c10f_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testInitElProvider_whenElProviderIsNull_thenElProviderIsInitialized() {
        // Act
        defaultDmnEngineConfiguration.initElProvider();

        // Assert
        ElProvider elProvider = defaultDmnEngineConfiguration.getElProvider();
        assertNotNull(elProvider);
        assertTrue(elProvider instanceof JuelElProvider);
    }

    @Test
    public void testInitElProvider_whenElProviderIsNotNull_thenElProviderIsNotReinitialized() {
        // Arrange
        ElProvider initialElProvider = new JuelElProvider();
        defaultDmnEngineConfiguration.setElProvider(initialElProvider);

        // Act
        defaultDmnEngineConfiguration.initElProvider();

        // Assert
        ElProvider elProvider = defaultDmnEngineConfiguration.getElProvider();
        assertSame(initialElProvider, elProvider);
    }
}
