// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class DefaultDmnEngineConfiguration_setDefaultLiteralExpressionLanguage_a657e3d7ba_Test {

    @InjectMocks
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setup() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testSetDefaultLiteralExpressionLanguage_Success() {
        // TODO: replace "expressionLanguage" with the actual expression language you want to set
        String expressionLanguage = "expressionLanguage";
        defaultDmnEngineConfiguration.setDefaultLiteralExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, defaultDmnEngineConfiguration.getDefaultLiteralExpressionLanguage());
    }

    @Test
    public void testSetDefaultLiteralExpressionLanguage_Null() {
        assertThrows(NullPointerException.class, () -> {
            defaultDmnEngineConfiguration.setDefaultLiteralExpressionLanguage(null);
        });
    }
}
