// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class DefaultDmnEngineConfiguration_enableFeelLegacyBehavior_e7f1a1b1a7_Test {
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testEnableFeelLegacyBehavior_True() {
        defaultDmnEngineConfiguration.enableFeelLegacyBehavior(true);
        assertEquals(true, defaultDmnEngineConfiguration.isEnableFeelLegacyBehavior());
    }

    @Test
    public void testEnableFeelLegacyBehavior_False() {
        defaultDmnEngineConfiguration.enableFeelLegacyBehavior(false);
        assertEquals(false, defaultDmnEngineConfiguration.isEnableFeelLegacyBehavior());
    }
}
