// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.camunda.bpm.dmn.engine.delegate.DmnDecisionTableEvaluationListener;
import static org.junit.jupiter.api.Assertions.assertEquals;
import java.util.ArrayList;
import java.util.List;

public class DefaultDmnEngineConfiguration_getCustomPostDecisionTableEvaluationListeners_206e4d8053_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private List<DmnDecisionTableEvaluationListener> customPostDecisionTableEvaluationListeners;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = Mockito.mock(DefaultDmnEngineConfiguration.class);
        customPostDecisionTableEvaluationListeners = new ArrayList<>();
        customPostDecisionTableEvaluationListeners.add(Mockito.mock(DmnDecisionTableEvaluationListener.class));
        customPostDecisionTableEvaluationListeners.add(Mockito.mock(DmnDecisionTableEvaluationListener.class));
        Mockito.when(defaultDmnEngineConfiguration.getCustomPostDecisionTableEvaluationListeners()).thenReturn(customPostDecisionTableEvaluationListeners);
    }

    @Test
    public void testGetCustomPostDecisionTableEvaluationListeners_Success() {
        List<DmnDecisionTableEvaluationListener> response = defaultDmnEngineConfiguration.getCustomPostDecisionTableEvaluationListeners();
        assertEquals(customPostDecisionTableEvaluationListeners, response);
    }

    @Test
    public void testGetCustomPostDecisionTableEvaluationListeners_EmptyList() {
        customPostDecisionTableEvaluationListeners.clear();
        List<DmnDecisionTableEvaluationListener> response = defaultDmnEngineConfiguration.getCustomPostDecisionTableEvaluationListeners();
        assertEquals(customPostDecisionTableEvaluationListeners, response);
    }
}
