// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.delegate.DmnDecisionTableEvaluationListener;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;

import java.util.ArrayList;
import java.util.List;

public class DefaultDmnEngineConfiguration_customPreDecisionTableEvaluationListeners_44ce9cea07_Test {
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private List<DmnDecisionTableEvaluationListener> decisionTableEvaluationListeners;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        decisionTableEvaluationListeners = new ArrayList<>();
        decisionTableEvaluationListeners.add(Mockito.mock(DmnDecisionTableEvaluationListener.class));
        decisionTableEvaluationListeners.add(Mockito.mock(DmnDecisionTableEvaluationListener.class));
    }

    @Test
    public void testCustomPreDecisionTableEvaluationListeners() {
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.customPreDecisionTableEvaluationListeners(decisionTableEvaluationListeners);
        Assert.assertEquals(defaultDmnEngineConfiguration, result);
        Assert.assertEquals(decisionTableEvaluationListeners, defaultDmnEngineConfiguration.getCustomPreDecisionTableEvaluationListeners());
    }

    @Test
    public void testCustomPreDecisionTableEvaluationListenersWithNull() {
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.customPreDecisionTableEvaluationListeners(null);
        Assert.assertEquals(defaultDmnEngineConfiguration, result);
        Assert.assertNull(defaultDmnEngineConfiguration.getCustomPreDecisionTableEvaluationListeners());
    }
}
