// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.delegate.DmnDecisionEvaluationListener;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;
import java.util.ArrayList;
import java.util.List;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

public class DefaultDmnEngineConfiguration_initDecisionEvaluationListener_18fa78e60c_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private List<DmnDecisionEvaluationListener> customPreDecisionEvaluationListeners;
    private List<DmnDecisionEvaluationListener> customPostDecisionEvaluationListeners;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        customPreDecisionEvaluationListeners = new ArrayList<>();
        customPostDecisionEvaluationListeners = new ArrayList<>();
    }

    @Test
    public void testInitDecisionEvaluationListener_WithPreAndPostListeners() {
        DmnDecisionEvaluationListener preListener = Mockito.mock(DmnDecisionEvaluationListener.class);
        DmnDecisionEvaluationListener postListener = Mockito.mock(DmnDecisionEvaluationListener.class);
        customPreDecisionEvaluationListeners.add(preListener);
        customPostDecisionEvaluationListeners.add(postListener);

        defaultDmnEngineConfiguration.setCustomPreDecisionEvaluationListeners(customPreDecisionEvaluationListeners);
        defaultDmnEngineConfiguration.setCustomPostDecisionEvaluationListeners(customPostDecisionEvaluationListeners);

        defaultDmnEngineConfiguration.initDecisionEvaluationListener();

        List<DmnDecisionEvaluationListener> listeners = defaultDmnEngineConfiguration.getDecisionEvaluationListeners();
        assertEquals(3, listeners.size());
        assertEquals(preListener, listeners.get(0));
        assertEquals(postListener, listeners.get(2));
    }

    @Test
    public void testInitDecisionEvaluationListener_WithoutPreAndPostListeners() {
        defaultDmnEngineConfiguration.initDecisionEvaluationListener();

        List<DmnDecisionEvaluationListener> listeners = defaultDmnEngineConfiguration.getDecisionEvaluationListeners();
        assertEquals(1, listeners.size());
    }
}
