// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.camunda.bpm.dmn.engine.impl.spi.el.ElProvider;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class DefaultDmnEngineConfiguration_getElProvider_05893847c4_Test {

    @Mock
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    private ElProvider elProvider;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
        when(defaultDmnEngineConfiguration.getElProvider()).thenReturn(elProvider);
    }

    @Test
    public void testGetElProvider_success() {
        ElProvider result = defaultDmnEngineConfiguration.getElProvider();
        assertEquals(elProvider, result, "Expected and actual ElProvider should match");
    }

    @Test
    public void testGetElProvider_failure() {
        when(defaultDmnEngineConfiguration.getElProvider()).thenReturn(null);
        ElProvider result = defaultDmnEngineConfiguration.getElProvider();
        assertEquals(null, result, "Expected null when ElProvider is not set");
    }
}
