// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class DefaultDmnEngineConfiguration_setDefaultInputExpressionExpressionLanguage_1ad11dbc14_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testSetDefaultInputExpressionExpressionLanguage() {
        String expressionLanguage = "Python";
        defaultDmnEngineConfiguration.setDefaultInputExpressionExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, defaultDmnEngineConfiguration.getDefaultInputExpressionExpressionLanguage());
    }

    @Test
    public void testSetDefaultInputExpressionExpressionLanguage_Null() {
        String expressionLanguage = null;
        defaultDmnEngineConfiguration.setDefaultInputExpressionExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, defaultDmnEngineConfiguration.getDefaultInputExpressionExpressionLanguage());
    }
}
