// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.impl.metrics.DefaultEngineMetricCollector;
import org.camunda.bpm.dmn.engine.spi.DmnEngineMetricCollector;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import static org.junit.Assert.*;

@RunWith(SpringRunner.class)
@SpringBootTest
public class DefaultDmnEngineConfiguration_initMetricCollector_4b9982633b_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testInitMetricCollector_whenEngineMetricCollectorIsNull() {
        defaultDmnEngineConfiguration.initMetricCollector();

        DmnEngineMetricCollector result = defaultDmnEngineConfiguration.getEngineMetricCollector();

        assertNotNull(result);
        assertTrue(result instanceof DefaultEngineMetricCollector);
    }

    @Test
    public void testInitMetricCollector_whenEngineMetricCollectorIsNotNull() {
        DmnEngineMetricCollector mockMetricCollector = new DefaultEngineMetricCollector();
        defaultDmnEngineConfiguration.setEngineMetricCollector(mockMetricCollector);

        defaultDmnEngineConfiguration.initMetricCollector();

        DmnEngineMetricCollector result = defaultDmnEngineConfiguration.getEngineMetricCollector();

        assertSame(mockMetricCollector, result);
    }
}
