// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.impl.spi.transform.DmnTransformer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class DefaultDmnEngineConfiguration_setTransformer_383dbab3fa_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private DmnTransformer mockTransformer;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        mockTransformer = mock(DmnTransformer.class);
    }

    @Test
    public void testSetTransformer_Success() {
        defaultDmnEngineConfiguration.setTransformer(mockTransformer);
        assertEquals(mockTransformer, defaultDmnEngineConfiguration.getTransformer());
    }

    @Test
    public void testSetTransformer_Null() {
        defaultDmnEngineConfiguration.setTransformer(null);
        assertNull(defaultDmnEngineConfiguration.getTransformer());
    }
}
