// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.impl.spi.el.ElProvider;
import org.camunda.bpm.dmn.engine.impl.el.JuelElProvider;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class DefaultDmnEngineConfiguration_initElProvider_e7ed92c10f_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testInitElProviderWhenElProviderIsNull() {
        defaultDmnEngineConfiguration.initElProvider();
        ElProvider elProvider = defaultDmnEngineConfiguration.getElProvider();
        assertTrue(elProvider instanceof JuelElProvider);
    }

    @Test
    public void testInitElProviderWhenElProviderIsNotNull() {
        ElProvider mockElProvider = Mockito.mock(ElProvider.class);
        defaultDmnEngineConfiguration.setElProvider(mockElProvider);
        defaultDmnEngineConfiguration.initElProvider();
        ElProvider elProvider = defaultDmnEngineConfiguration.getElProvider();
        assertEquals(mockElProvider, elProvider);
    }
}
