// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.impl.metrics.DefaultEngineMetricCollector;
import org.camunda.bpm.dmn.engine.impl.metrics.DmnEngineMetricCollectorWrapper;
import org.camunda.bpm.dmn.engine.spi.DmnEngineMetricCollector;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;

public class DefaultDmnEngineConfiguration_engineMetricCollector_e1d90ecaa2_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private DmnEngineMetricCollector engineMetricCollector;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        engineMetricCollector = Mockito.mock(DmnEngineMetricCollector.class);
    }

    @Test
    public void testEngineMetricCollectorSuccess() {
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.engineMetricCollector(engineMetricCollector);
        Assert.assertNotNull(result);
        Assert.assertEquals(defaultDmnEngineConfiguration, result);
    }

    @Test
    public void testEngineMetricCollectorFailure() {
        try {
            defaultDmnEngineConfiguration.engineMetricCollector(null);
        } catch (IllegalArgumentException e) {
            Assert.assertEquals("EngineMetricCollector cannot be null", e.getMessage());
        }
    }
}
