// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.impl.spi.el.ElProvider;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class DefaultDmnEngineConfiguration_getElProvider_05893847c4_Test {

    @Mock
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    private ElProvider elProviderMock;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        elProviderMock = new JuelElProvider();
        when(defaultDmnEngineConfiguration.getElProvider()).thenReturn(elProviderMock);
    }

    @Test
    public void testGetElProvider_Success() {
        ElProvider result = defaultDmnEngineConfiguration.getElProvider();
        assertEquals(elProviderMock, result);
    }

    @Test
    public void testGetElProvider_Failure() {
        when(defaultDmnEngineConfiguration.getElProvider()).thenReturn(null);
        ElProvider result = defaultDmnEngineConfiguration.getElProvider();
        assertEquals(null, result);
    }
}
