// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.impl.el.DefaultScriptEngineResolver;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

import static org.junit.Assert.assertNotNull;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class DefaultDmnEngineConfiguration_initScriptEngineResolver_3ea497e2ed_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    private DefaultScriptEngineResolver scriptEngineResolver;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testInitScriptEngineResolver_whenScriptEngineResolverIsNull() {
        defaultDmnEngineConfiguration.initScriptEngineResolver();
        assertNotNull(defaultDmnEngineConfiguration.getScriptEngineResolver());
    }

    @Test
    public void testInitScriptEngineResolver_whenScriptEngineResolverIsNotNull() {
        when(scriptEngineResolver.isInitialized()).thenReturn(true);
        defaultDmnEngineConfiguration.setScriptEngineResolver(scriptEngineResolver);
        defaultDmnEngineConfiguration.initScriptEngineResolver();
        assertNotNull(defaultDmnEngineConfiguration.getScriptEngineResolver());
    }
}
