// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.camunda.bpm.dmn.engine.delegate.DmnDecisionEvaluationListener;
import java.util.Arrays;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class DefaultDmnEngineConfiguration_customPreDecisionEvaluationListeners_6072666df9_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private DmnDecisionEvaluationListener decisionEvaluationListener;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        decisionEvaluationListener = Mockito.mock(DmnDecisionEvaluationListener.class);
    }

    @Test
    public void testCustomPreDecisionEvaluationListeners_withValidListeners() {
        List<DmnDecisionEvaluationListener> decisionEvaluationListeners = Arrays.asList(decisionEvaluationListener, decisionEvaluationListener);
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.customPreDecisionEvaluationListeners(decisionEvaluationListeners);
        assertEquals(defaultDmnEngineConfiguration, result);
        assertEquals(decisionEvaluationListeners, defaultDmnEngineConfiguration.getCustomPreDecisionEvaluationListeners());
    }

    @Test
    public void testCustomPreDecisionEvaluationListeners_withNullListeners() {
        List<DmnDecisionEvaluationListener> decisionEvaluationListeners = null;
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.customPreDecisionEvaluationListeners(decisionEvaluationListeners);
        assertEquals(defaultDmnEngineConfiguration, result);
        assertEquals(decisionEvaluationListeners, defaultDmnEngineConfiguration.getCustomPreDecisionEvaluationListeners());
    }
}
