// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.camunda.bpm.dmn.engine.impl.spi.el.DmnScriptEngineResolver;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

public class DefaultDmnEngineConfiguration_setScriptEngineResolver_6419ba0be3_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private DmnScriptEngineResolver scriptEngineResolver;

    @BeforeEach
    public void setup() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        scriptEngineResolver = Mockito.mock(DmnScriptEngineResolver.class);
    }

    @Test
    public void testSetScriptEngineResolver() {
        defaultDmnEngineConfiguration.setScriptEngineResolver(scriptEngineResolver);
        DmnScriptEngineResolver actual = defaultDmnEngineConfiguration.getScriptEngineResolver();
        assertEquals(scriptEngineResolver, actual);
    }

    @Test
    public void testSetScriptEngineResolver_Null() {
        defaultDmnEngineConfiguration.setScriptEngineResolver(null);
        DmnScriptEngineResolver actual = defaultDmnEngineConfiguration.getScriptEngineResolver();
        assertNull(actual);
    }
}
