// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.camunda.bpm.dmn.engine.impl.spi.el.DmnScriptEngineResolver;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class DefaultDmnEngineConfiguration_getScriptEngineResolver_25634dd9ac_Test {

    @InjectMocks
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    private DmnScriptEngineResolver scriptEngineResolver;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration.setScriptEngineResolver(scriptEngineResolver);
    }

    @Test
    public void testGetScriptEngineResolver() {
        DmnScriptEngineResolver result = defaultDmnEngineConfiguration.getScriptEngineResolver();
        assertEquals(scriptEngineResolver, result);
    }

    @Test(expected = NullPointerException.class)
    public void testGetScriptEngineResolver_Null() {
        when(scriptEngineResolver.someMethod()).thenThrow(NullPointerException.class);
        defaultDmnEngineConfiguration.getScriptEngineResolver();
    }
}
