// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class DefaultDmnEngineConfiguration_defaultInputEntryExpressionLanguage_b4bb43c2b6_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testDefaultInputEntryExpressionLanguage_withValidExpressionLanguage() {
        String expressionLanguage = "ValidExpressionLanguage";
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.defaultInputEntryExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, defaultDmnEngineConfiguration.getDefaultInputEntryExpressionLanguage());
        assertEquals(defaultDmnEngineConfiguration, result);
    }

    @Test
    public void testDefaultInputEntryExpressionLanguage_withNullExpressionLanguage() {
        String expressionLanguage = null;
        assertThrows(NullPointerException.class, () -> defaultDmnEngineConfiguration.defaultInputEntryExpressionLanguage(expressionLanguage));
    }
}
