// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class DefaultDmnEngineConfiguration_setDefaultInputExpressionExpressionLanguage_1ad11dbc14_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setup() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testSetDefaultInputExpressionExpressionLanguage_ValidInput() {
        String expressionLanguage = "FEEL";
        defaultDmnEngineConfiguration.setDefaultInputExpressionExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, defaultDmnEngineConfiguration.getDefaultInputExpressionExpressionLanguage());
    }

    @Test
    public void testSetDefaultInputExpressionExpressionLanguage_NullInput() {
        String expressionLanguage = null;
        defaultDmnEngineConfiguration.setDefaultInputExpressionExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, defaultDmnEngineConfiguration.getDefaultInputExpressionExpressionLanguage());
    }
}
