// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.impl.spi.el.DmnScriptEngineResolver;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

@RunWith(MockitoJUnitRunner.class)
public class DefaultDmnEngineConfiguration_setScriptEngineResolver_6419ba0be3_Test {

    @InjectMocks
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    private DmnScriptEngineResolver scriptEngineResolver;

    @Before
    public void setUp() throws Exception {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testSetScriptEngineResolver() {
        defaultDmnEngineConfiguration.setScriptEngineResolver(scriptEngineResolver);
        assertEquals(scriptEngineResolver, defaultDmnEngineConfiguration.scriptEngineResolver);
    }

    @Test(expected = NullPointerException.class)
    public void testSetScriptEngineResolver_Null() {
        defaultDmnEngineConfiguration.setScriptEngineResolver(null);
    }
}
