// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThrows;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.camunda.bpm.dmn.engine.DmnDecision;
import org.camunda.bpm.dmn.engine.DmnDecisionResult;
import org.camunda.bpm.dmn.engine.impl.spi.transform.DmnTransformer;
import org.camunda.bpm.engine.variable.context.VariableContext;
import org.camunda.bpm.engine.variable.Variables;
import org.junit.Before;
import org.junit.Test;

public class DefaultDmnEngine_evaluateDecision_69d4b7215f_Test {

    private DefaultDmnEngine testEngine;
    private DmnDecision decision;
    private VariableContext variableContext;

    @Before
    public void setup() {
        testEngine = new DefaultDmnEngine();
        decision = mock(DmnDecision.class);
        variableContext = Variables.putValue("testVariable", "testValue").create();
    }

    @Test
    public void testEvaluateDecision_Success() {
        when(decision instanceof DmnDecisionImpl).thenReturn(true);
        DmnDecisionResult result = testEngine.evaluateDecision(decision, variableContext);
        assertEquals("Expected Result", result);
    }

    @Test
    public void testEvaluateDecision_Failure() {
        when(decision instanceof DmnDecisionImpl).thenReturn(false);
        Exception exception = assertThrows(RuntimeException.class, () -> {
            testEngine.evaluateDecision(decision, variableContext);
        });
        assertEquals("Decision type not supported", exception.getMessage());
    }
}
