// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.*;

import java.util.HashMap;
import java.util.Map;

import org.camunda.bpm.dmn.engine.DmnDecision;
import org.camunda.bpm.dmn.engine.DmnDecisionTableResult;
import org.camunda.bpm.engine.variable.Variables;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class DefaultDmnEngine_evaluateDecisionTable_864748667b_Test {

    @InjectMocks
    DefaultDmnEngine defaultDmnEngine;

    @Mock
    DmnDecision decision;

    @Mock
    DmnDecisionTableResult decisionTableResult;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testEvaluateDecisionTableSuccess() {
        Map<String, Object> variables = new HashMap<>();
        variables.put("variable1", "value1");
        variables.put("variable2", "value2");

        when(defaultDmnEngine.evaluateDecisionTable(decision, Variables.fromMap(variables).asVariableContext())).thenReturn(decisionTableResult);

        DmnDecisionTableResult result = defaultDmnEngine.evaluateDecisionTable(decision, variables);

        assertEquals(decisionTableResult, result);
    }

    @Test
    public void testEvaluateDecisionTableWithNullDecision() {
        Map<String, Object> variables = new HashMap<>();
        variables.put("variable1", "value1");
        variables.put("variable2", "value2");

        assertThrows(IllegalArgumentException.class, () -> {
            defaultDmnEngine.evaluateDecisionTable(null, variables);
        });
    }

    @Test
    public void testEvaluateDecisionTableWithNullVariables() {
        assertThrows(IllegalArgumentException.class, () -> {
            defaultDmnEngine.evaluateDecisionTable(decision, null);
        });
    }

}
