// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.camunda.bpm.dmn.engine.DmnEngineConfiguration;
import org.junit.Before;
import org.junit.Test;

public class DefaultDmnEngine_getConfiguration_0300abcca9_Test {

    private DefaultDmnEngine defaultDmnEngine;
    private DmnEngineConfiguration dmnEngineConfiguration;

    @Before
    public void setUp() {
        dmnEngineConfiguration = mock(DmnEngineConfiguration.class);
        defaultDmnEngine = new DefaultDmnEngine(dmnEngineConfiguration);
    }

    @Test
    public void testGetConfiguration_whenConfigurationIsSet() {
        DmnEngineConfiguration result = defaultDmnEngine.getConfiguration();
        assertEquals(dmnEngineConfiguration, result);
    }

    @Test
    public void testGetConfiguration_whenConfigurationIsNull() {
        defaultDmnEngine = new DefaultDmnEngine(null);
        DmnEngineConfiguration result = defaultDmnEngine.getConfiguration();
        assertEquals(null, result);
    }
}
