// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;

import org.camunda.bpm.dmn.engine.DmnDecisionTableResult;
import org.camunda.bpm.engine.variable.Variables;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

class DefaultDmnEngine_evaluateDecisionTable_38e4626bff_Test {

    @InjectMocks
    DefaultDmnEngine defaultDmnEngine;

    @Mock
    InputStream inputStream;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    void testEvaluateDecisionTable_success() {
        String decisionKey = "decision1";
        Map<String, Object> variables = new HashMap<>();
        variables.put("var1", "value1");
        variables.put("var2", "value2");

        DmnDecisionTableResult result = defaultDmnEngine.evaluateDecisionTable(decisionKey, inputStream, variables);
        assertNotNull(result);
    }

    @Test
    void testEvaluateDecisionTable_nullVariables() {
        String decisionKey = "decision1";
        Map<String, Object> variables = null;

        assertThrows(IllegalArgumentException.class, () -> {
            defaultDmnEngine.evaluateDecisionTable(decisionKey, inputStream, variables);
        });
    }
}
