// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.feel.impl.FeelEngineFactory;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class DefaultDmnEngineConfiguration_getFeelEngineFactory_b0d7708340_Test {

    @Mock
    private FeelEngineFactory mockFeelEngineFactory;

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        defaultDmnEngineConfiguration.setFeelEngineFactory(mockFeelEngineFactory);
    }

    @Test
    public void testGetFeelEngineFactory_success() {
        FeelEngineFactory result = defaultDmnEngineConfiguration.getFeelEngineFactory();
        assertEquals(mockFeelEngineFactory, result);
    }

    @Test
    public void testGetFeelEngineFactory_failure() {
        defaultDmnEngineConfiguration.setFeelEngineFactory(null);
        assertNull(defaultDmnEngineConfiguration.getFeelEngineFactory());
    }
}
