// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.camunda.bpm.dmn.engine.impl.DefaultDmnEngineConfiguration;

public class DefaultDmnEngineConfiguration_getDefaultOutputEntryExpressionLanguage_b24daaa06f_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testGetDefaultOutputEntryExpressionLanguage_WhenValueIsSet() {
        String expectedValue = "expectedLanguage";
        defaultDmnEngineConfiguration.setDefaultOutputEntryExpressionLanguage(expectedValue);

        String actualValue = defaultDmnEngineConfiguration.getDefaultOutputEntryExpressionLanguage();

        assertEquals(expectedValue, actualValue);
    }

    @Test
    public void testGetDefaultOutputEntryExpressionLanguage_WhenValueIsNotSet() {
        String expectedValue = null;

        String actualValue = defaultDmnEngineConfiguration.getDefaultOutputEntryExpressionLanguage();

        assertEquals(expectedValue, actualValue);
    }
}
