// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.feel.impl.scala.function.FeelCustomFunctionProvider;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.verify;

@RunWith(MockitoJUnitRunner.class)
@SpringBootTest
public class DefaultDmnEngineConfiguration_feelCustomFunctionProviders_c023fb082e_Test {

    @Mock
    private FeelCustomFunctionProvider mockFeelCustomFunctionProvider;

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testFeelCustomFunctionProviders_withValidProviders() {
        List<FeelCustomFunctionProvider> feelCustomFunctionProviders = new ArrayList<>();
        feelCustomFunctionProviders.add(mockFeelCustomFunctionProvider);

        defaultDmnEngineConfiguration.feelCustomFunctionProviders(feelCustomFunctionProviders);

        assertEquals(feelCustomFunctionProviders, defaultDmnEngineConfiguration.getFeelCustomFunctionProviders());
    }

    @Test
    public void testFeelCustomFunctionProviders_withNullProviders() {
        defaultDmnEngineConfiguration.feelCustomFunctionProviders(null);

        assertEquals(null, defaultDmnEngineConfiguration.getFeelCustomFunctionProviders());
    }
}
