// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import java.util.ArrayList;
import java.util.List;
import org.camunda.bpm.dmn.engine.delegate.DmnDecisionTableEvaluationListener;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class DefaultDmnEngineConfiguration_getDecisionTableEvaluationListeners_e98ba8bf7f_Test {

    @InjectMocks
    DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    List<DmnDecisionTableEvaluationListener> decisionTableEvaluationListeners;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetDecisionTableEvaluationListeners_Success() {
        List<DmnDecisionTableEvaluationListener> listeners = new ArrayList<>();
        when(decisionTableEvaluationListeners.size()).thenReturn(2);
        when(defaultDmnEngineConfiguration.getDecisionTableEvaluationListeners()).thenReturn(listeners);
        assertEquals(listeners, defaultDmnEngineConfiguration.getDecisionTableEvaluationListeners());
    }

    @Test
    public void testGetDecisionTableEvaluationListeners_EmptyList() {
        List<DmnDecisionTableEvaluationListener> listeners = new ArrayList<>();
        when(decisionTableEvaluationListeners.size()).thenReturn(0);
        when(defaultDmnEngineConfiguration.getDecisionTableEvaluationListeners()).thenReturn(listeners);
        assertEquals(listeners, defaultDmnEngineConfiguration.getDecisionTableEvaluationListeners());
    }
}
