// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class DefaultDmnEngineConfiguration_defaultInputExpressionExpressionLanguage_ffb5b5d9d2_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setup() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testDefaultInputExpressionExpressionLanguage_withValidInput() {
        String expressionLanguage = "juel";
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.defaultInputExpressionExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, result.getDefaultInputExpressionExpressionLanguage());
    }

    @Test
    public void testDefaultInputExpressionExpressionLanguage_withNullInput() {
        String expressionLanguage = null;
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.defaultInputExpressionExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, result.getDefaultInputExpressionExpressionLanguage());
    }
}
