// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.camunda.bpm.dmn.engine.impl.spi.el.ElProvider;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

public class DefaultDmnEngineConfiguration_elProvider_091a424170_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private ElProvider elProvider;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        elProvider = Mockito.mock(ElProvider.class);
    }

    @Test
    public void testElProvider_Success() {
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.elProvider(elProvider);
        assertEquals(defaultDmnEngineConfiguration, result);
        verify(defaultDmnEngineConfiguration).setElProvider(elProvider);
    }

    @Test
    public void testElProvider_Null() {
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.elProvider(null);
        assertEquals(defaultDmnEngineConfiguration, result);
        verify(defaultDmnEngineConfiguration).setElProvider(null);
    }
}
