// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.camunda.bpm.dmn.engine.DmnDecisionRequirementsGraph;
import org.camunda.bpm.dmn.engine.impl.spi.transform.DmnTransformer;
import org.camunda.bpm.model.dmn.DmnModelInstance;
import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class DefaultDmnEngine_parseDecisionRequirementsGraph_393cf2fcbf_Test {

    @InjectMocks
    private DefaultDmnEngine defaultDmnEngine;

    @Mock
    private DmnTransformer transformer;

    @Before
    public void setUp() throws Exception {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testParseDecisionRequirementsGraph_Success() {
        DmnModelInstance dmnModelInstance = mock(DmnModelInstance.class);
        DmnDecisionRequirementsGraph dmnDecisionRequirementsGraph = mock(DmnDecisionRequirementsGraph.class);
        when(transformer.createTransform().modelInstance(dmnModelInstance).transformDecisionRequirementsGraph()).thenReturn(dmnDecisionRequirementsGraph);
        DmnDecisionRequirementsGraph result = defaultDmnEngine.parseDecisionRequirementsGraph(dmnModelInstance);
        assertNotNull(result);
        assertEquals(dmnDecisionRequirementsGraph, result);
    }

    @Test(expected = IllegalArgumentException.class)
    public void testParseDecisionRequirementsGraph_NullModelInstance() {
        defaultDmnEngine.parseDecisionRequirementsGraph(null);
    }
}
