// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import org.camunda.bpm.dmn.engine.delegate.DmnDecisionEvaluationListener;

import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.*;

@RunWith(MockitoJUnitRunner.class)
public class DefaultDmnEngineConfiguration_customPreDecisionEvaluationListeners_6072666df9_Test {

    @InjectMocks
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Mock
    private DmnDecisionEvaluationListener decisionEvaluationListener1;

    @Mock
    private DmnDecisionEvaluationListener decisionEvaluationListener2;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testCustomPreDecisionEvaluationListeners_WithValidInput() {
        List<DmnDecisionEvaluationListener> decisionEvaluationListeners = Arrays.asList(decisionEvaluationListener1, decisionEvaluationListener2);
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.customPreDecisionEvaluationListeners(decisionEvaluationListeners);
        assertEquals(defaultDmnEngineConfiguration, result);
    }

    @Test(expected = NullPointerException.class)
    public void testCustomPreDecisionEvaluationListeners_WithNullInput() {
        defaultDmnEngineConfiguration.customPreDecisionEvaluationListeners(null);
    }
}
