// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import org.camunda.bpm.dmn.engine.impl.spi.el.DmnScriptEngineResolver;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class DefaultDmnEngineConfiguration_scriptEngineResolver_d5a1a3338a_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private DmnScriptEngineResolver scriptEngineResolver;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        scriptEngineResolver = mock(DmnScriptEngineResolver.class);
    }

    @Test
    public void testScriptEngineResolver() {
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.scriptEngineResolver(scriptEngineResolver);
        verify(defaultDmnEngineConfiguration).setScriptEngineResolver(scriptEngineResolver);
        assertEquals(defaultDmnEngineConfiguration, result);
    }

    @Test
    public void testScriptEngineResolverWithNull() {
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.scriptEngineResolver(null);
        verify(defaultDmnEngineConfiguration).setScriptEngineResolver(null);
        assertEquals(defaultDmnEngineConfiguration, result);
    }
}
