// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class DefaultDmnEngineConfiguration_setDefaultInputEntryExpressionLanguage_19e58d54d9_Test {

    private DefaultDmnEngineConfiguration configuration;

    @BeforeEach
    public void setUp() {
        configuration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testSetDefaultInputEntryExpressionLanguage_ValidInput() {
        String expressionLanguage = "JUEL";
        configuration.setDefaultInputEntryExpressionLanguage(expressionLanguage);
        assertEquals(expressionLanguage, configuration.getDefaultInputEntryExpressionLanguage());
    }

    @Test
    public void testSetDefaultInputEntryExpressionLanguage_NullInput() {
        assertThrows(NullPointerException.class, () -> {
            configuration.setDefaultInputEntryExpressionLanguage(null);
        });
    }
}
