// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.impl.spi.transform.DmnTransformer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;

public class DefaultDmnEngineConfiguration_transformer_15e3000c13_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private DmnTransformer dmnTransformer;

    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        dmnTransformer = Mockito.mock(DmnTransformer.class);
    }

    @Test
    public void testTransformer() {
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.transformer(dmnTransformer);
        assertEquals(defaultDmnEngineConfiguration, result);
        assertEquals(dmnTransformer, defaultDmnEngineConfiguration.getTransformer());
    }

    @Test
    public void testTransformer_NullInput() {
        DefaultDmnEngineConfiguration result = defaultDmnEngineConfiguration.transformer(null);
        assertEquals(defaultDmnEngineConfiguration, result);
        assertNull(defaultDmnEngineConfiguration.getTransformer());
    }
}
