// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class DefaultDmnEngineConfiguration_setDefaultInputEntryExpressionLanguage_19e58d54d9_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @BeforeEach
    public void setup() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testSetDefaultInputEntryExpressionLanguage_ValidExpressionLanguage() {
        String validExpressionLanguage = "FEEL";
        defaultDmnEngineConfiguration.setDefaultInputEntryExpressionLanguage(validExpressionLanguage);
        assertEquals(validExpressionLanguage, defaultDmnEngineConfiguration.getDefaultInputEntryExpressionLanguage());
    }

    @Test
    public void testSetDefaultInputEntryExpressionLanguage_NullExpressionLanguage() {
        String nullExpressionLanguage = null;
        defaultDmnEngineConfiguration.setDefaultInputEntryExpressionLanguage(nullExpressionLanguage);
        assertEquals(nullExpressionLanguage, defaultDmnEngineConfiguration.getDefaultInputEntryExpressionLanguage());
    }
}
