// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.feel.impl.FeelEngine;
import org.camunda.bpm.dmn.feel.impl.FeelEngineFactory;
import org.camunda.bpm.dmn.feel.impl.juel.FeelEngineFactoryImpl;
import org.camunda.bpm.dmn.feel.impl.scala.ScalaFeelEngineFactory;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;

import static org.junit.Assert.*;
import static org.mockito.Mockito.when;

public class DefaultDmnEngineConfiguration_initFeelEngine_b2c280d088_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private ScalaFeelEngineFactory scalaFeelEngineFactory;
    private FeelEngineFactoryImpl feelEngineFactoryImpl;
    private FeelEngine feelEngine;

    @Before
    public void setup() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
        scalaFeelEngineFactory = Mockito.mock(ScalaFeelEngineFactory.class);
        feelEngineFactoryImpl = Mockito.mock(FeelEngineFactoryImpl.class);
        feelEngine = Mockito.mock(FeelEngine.class);
    }

    @Test
    public void testInitFeelEngine_withScalaFeelEngineFactory() {
        when(scalaFeelEngineFactory.createInstance()).thenReturn(feelEngine);
        defaultDmnEngineConfiguration.setFeelEngineFactory(scalaFeelEngineFactory);
        defaultDmnEngineConfiguration.setEnableFeelLegacyBehavior(false);

        defaultDmnEngineConfiguration.initFeelEngine();

        assertSame(feelEngine, defaultDmnEngineConfiguration.getFeelEngine());
    }

    @Test
    public void testInitFeelEngine_withFeelEngineFactoryImpl() {
        when(feelEngineFactoryImpl.createInstance()).thenReturn(feelEngine);
        defaultDmnEngineConfiguration.setFeelEngineFactory(feelEngineFactoryImpl);
        defaultDmnEngineConfiguration.setEnableFeelLegacyBehavior(true);

        defaultDmnEngineConfiguration.initFeelEngine();

        assertSame(feelEngine, defaultDmnEngineConfiguration.getFeelEngine());
    }
}
