// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import static org.junit.Assert.assertEquals;

@RunWith(SpringRunner.class)
@SpringBootTest
public class DefaultDmnEngineConfiguration_setEnableFeelLegacyBehavior_d5973adc0b_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;

    @Before
    public void setUp() {
        defaultDmnEngineConfiguration = new DefaultDmnEngineConfiguration();
    }

    @Test
    public void testSetEnableFeelLegacyBehavior_True() {
        defaultDmnEngineConfiguration.setEnableFeelLegacyBehavior(true);
        assertEquals(true, defaultDmnEngineConfiguration.isEnableFeelLegacyBehavior());
    }

    @Test
    public void testSetEnableFeelLegacyBehavior_False() {
        defaultDmnEngineConfiguration.setEnableFeelLegacyBehavior(false);
        assertEquals(false, defaultDmnEngineConfiguration.isEnableFeelLegacyBehavior());
    }
}
