// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.camunda.bpm.dmn.feel.impl.scala.function.FeelCustomFunctionProvider;
import java.util.ArrayList;
import java.util.List;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class DefaultDmnEngineConfiguration_getFeelCustomFunctionProviders_29ee054ed0_Test {

    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    private List<FeelCustomFunctionProvider> feelCustomFunctionProviders;

    @BeforeEach
    public void setup() {
        defaultDmnEngineConfiguration = Mockito.mock(DefaultDmnEngineConfiguration.class);
        feelCustomFunctionProviders = new ArrayList<>();
        feelCustomFunctionProviders.add(Mockito.mock(FeelCustomFunctionProvider.class));
        feelCustomFunctionProviders.add(Mockito.mock(FeelCustomFunctionProvider.class));
        when(defaultDmnEngineConfiguration.getFeelCustomFunctionProviders()).thenReturn(feelCustomFunctionProviders);
    }

    @Test
    public void testGetFeelCustomFunctionProvidersSuccess() {
        List<FeelCustomFunctionProvider> result = defaultDmnEngineConfiguration.getFeelCustomFunctionProviders();
        assertEquals(feelCustomFunctionProviders, result);
    }

    @Test
    public void testGetFeelCustomFunctionProvidersFailure() {
        when(defaultDmnEngineConfiguration.getFeelCustomFunctionProviders()).thenReturn(null);
        List<FeelCustomFunctionProvider> result = defaultDmnEngineConfiguration.getFeelCustomFunctionProviders();
        assertEquals(null, result);
    }
}
