// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.Mockito;

public class DefaultDmnEngineConfiguration_getDefaultLiteralExpressionLanguage_2d0f61b0cd_Test {
    
    private DefaultDmnEngineConfiguration defaultDmnEngineConfiguration;
    
    @BeforeEach
    public void setUp() {
        defaultDmnEngineConfiguration = Mockito.spy(new DefaultDmnEngineConfiguration());
    }
    
    @Test
    public void testGetDefaultLiteralExpressionLanguage() {
        String expectedOutput = "Expected Output";
        Mockito.doReturn(expectedOutput).when(defaultDmnEngineConfiguration).getDefaultLiteralExpressionLanguage();
        String actualOutput = defaultDmnEngineConfiguration.getDefaultLiteralExpressionLanguage();
        assertEquals(expectedOutput, actualOutput);
    }
    
    @Test
    public void testGetDefaultLiteralExpressionLanguage_NullCase() {
        Mockito.doReturn(null).when(defaultDmnEngineConfiguration).getDefaultLiteralExpressionLanguage();
        String actualOutput = defaultDmnEngineConfiguration.getDefaultLiteralExpressionLanguage();
        assertEquals(null, actualOutput);
    }
}
