// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.DmnDecisionLogic;
import org.camunda.bpm.dmn.engine.impl.spi.type.DmnVariableImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class DmnDecisionLiteralExpressionImpl_getVariable_12805bd663_Test {

    private DmnDecisionLiteralExpressionImpl dmnDecisionLiteralExpressionImpl;
    private DmnVariableImpl variable;

    @BeforeEach
    public void setUp() {
        dmnDecisionLiteralExpressionImpl = new DmnDecisionLiteralExpressionImpl();
        variable = new DmnVariableImpl("testVariable");
        dmnDecisionLiteralExpressionImpl.setVariable(variable);
    }

    @Test
    public void testGetVariable_Success() {
        DmnVariableImpl result = dmnDecisionLiteralExpressionImpl.getVariable();
        assertNotNull(result);
        assertEquals(variable, result);
    }

    @Test
    public void testGetVariable_Failure() {
        dmnDecisionLiteralExpressionImpl.setVariable(null);
        DmnVariableImpl result = dmnDecisionLiteralExpressionImpl.getVariable();
        assertNull(result);
    }
}
