// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(SpringExtension.class)
@SpringBootTest
public class DmnDecisionImpl_getKey_d9b1f905c5_Test {

    @InjectMocks
    private DmnDecisionImpl dmnDecisionImpl;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        dmnDecisionImpl = new DmnDecisionImpl();
    }

    @Test
    public void testGetKey_success() {
        String expectedKey = "testKey";
        dmnDecisionImpl.setKey(expectedKey);
        String actualKey = dmnDecisionImpl.getKey();

        assertEquals(expectedKey, actualKey, "The key returned by getKey method does not match the expected value");
    }

    @Test
    public void testGetKey_null() {
        String expectedKey = null;
        dmnDecisionImpl.setKey(expectedKey);
        String actualKey = dmnDecisionImpl.getKey();

        assertEquals(expectedKey, actualKey, "The key returned by getKey method does not match the expected value");
    }
}
