// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;
import org.camunda.bpm.dmn.engine.DmnDecisionLogic;

class DmnDecisionImpl_getDecisionLogic_55dc7690b4_Test {

    private DmnDecisionImpl decisionImpl;
    private DmnDecisionLogic decisionLogicMock;

    @BeforeEach
    void setUp() {
        decisionLogicMock = Mockito.mock(DmnDecisionLogic.class);
        decisionImpl = new DmnDecisionImpl();
        decisionImpl.setDecisionLogic(decisionLogicMock);
    }

    @Test
    void testGetDecisionLogic_Success() {
        assertEquals(decisionLogicMock, decisionImpl.getDecisionLogic());
    }

    @Test
    void testGetDecisionLogic_Null() {
        decisionImpl.setDecisionLogic(null);
        assertEquals(null, decisionImpl.getDecisionLogic());
    }
}
