// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class DmnDecisionImpl_getKey_d9b1f905c5_Test {

    private DmnDecisionImpl dmnDecisionImpl;

    @BeforeEach
    public void setup() {
        dmnDecisionImpl = new DmnDecisionImpl();
    }

    @Test
    public void testGetKeyWhenKeyIsSet() {
        // TODO: Replace "expectedKey" with the actual key you want to set for testing
        String expectedKey = "expectedKey";
        dmnDecisionImpl.setKey(expectedKey);
        String actualKey = dmnDecisionImpl.getKey();
        assertEquals(expectedKey, actualKey);
    }

    @Test
    public void testGetKeyWhenKeyIsNotSet() {
        String expectedKey = null;
        String actualKey = dmnDecisionImpl.getKey();
        assertEquals(expectedKey, actualKey);
    }
}
