// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class DmnDecisionImpl_toString_2393b88875_Test {

    private DmnDecisionImpl dmnDecisionImpl;

    @Mock
    private DmnDecision requiredDecision;

    @Mock
    private DmnDecisionLogic decisionLogic;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        dmnDecisionImpl = new DmnDecisionImpl();
    }

    @Test
    public void testToString() {
        String key = "testKey";
        String name = "testName";
        dmnDecisionImpl.setKey(key);
        dmnDecisionImpl.setName(name);
        dmnDecisionImpl.setRequiredDecision(requiredDecision);
        dmnDecisionImpl.setDecisionLogic(decisionLogic);

        String expected = "DmnDecisionTableImpl{" +
                " key= "+ key +
                ", name= "+ name +
                ", requiredDecision=" + requiredDecision +
                ", decisionLogic=" + decisionLogic +
                '}';

        assertEquals(expected, dmnDecisionImpl.toString());
    }

    @Test
    public void testToString_NullValues() {
        dmnDecisionImpl.setKey(null);
        dmnDecisionImpl.setName(null);
        dmnDecisionImpl.setRequiredDecision(null);
        dmnDecisionImpl.setDecisionLogic(null);

        String expected = "DmnDecisionTableImpl{" +
                " key= null" +
                ", name= null" +
                ", requiredDecision=null" +
                ", decisionLogic=null" +
                '}';

        assertEquals(expected, dmnDecisionImpl.toString());
    }
}
