// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class DmnDecisionImpl_getName_4ad76af4d7_Test {

    @Mock
    private DmnDecisionImpl dmnDecision;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetName_Success() {
        String expectedName = "Test Decision";
        when(dmnDecision.getName()).thenReturn(expectedName);

        String actualName = dmnDecision.getName();

        assertEquals(expectedName, actualName, "The returned name should match the expected name");
    }

    @Test
    public void testGetName_Null() {
        String expectedName = null;
        when(dmnDecision.getName()).thenReturn(expectedName);

        String actualName = dmnDecision.getName();

        assertEquals(expectedName, actualName, "The returned name should be null");
    }
}
