// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.camunda.bpm.dmn.engine.DmnDecision;

public class DmnDecisionImpl_setKey_fcdc505e77_Test {

    private DmnDecisionImpl dmnDecisionImpl;

    @BeforeEach
    public void setUp() {
        dmnDecisionImpl = new DmnDecisionImpl();
    }

    @Test
    public void testSetKey_WithValidKey() {
        String key = "validKey";
        dmnDecisionImpl.setKey(key);
        assertEquals(key, dmnDecisionImpl.getKey());
    }

    @Test
    public void testSetKey_WithEmptyKey() {
        String key = "";
        dmnDecisionImpl.setKey(key);
        assertEquals(key, dmnDecisionImpl.getKey());
    }
}
