// Test regenerated by OpenAI for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.Assert.*;

public class DmnDecisionImpl_setKey_fcdc505e77_Test {

    @InjectMocks
    private DmnDecisionImpl dmnDecisionImpl;

    @Before
    public void setUp() throws Exception {
        MockitoAnnotations.initMocks(this);
        dmnDecisionImpl = new DmnDecisionImpl();
    }

    @Test
    public void testSetKey_success() {
        String expectedKey = "TestKey";
        dmnDecisionImpl.setKey(expectedKey);
        assertEquals(expectedKey, dmnDecisionImpl.getKey());
    }

    @Test
    public void testSetKey_null() {
        String expectedKey = null;
        dmnDecisionImpl.setKey(expectedKey);
        assertNull(dmnDecisionImpl.getKey());
    }
}
