// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import org.camunda.bpm.dmn.engine.DmnDecisionLogic;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.*;

@RunWith(MockitoJUnitRunner.class)
public class DmnDecisionImpl_setDecisionLogic_9ae9040465_Test {

    @InjectMocks
    DmnDecisionImpl dmnDecisionImpl;

    @Mock
    DmnDecisionLogic decisionLogic;

    @Before
    public void setUp() throws Exception {
        // TODO: setup necessary initializations if any
    }

    @Test
    public void testSetDecisionLogicSuccess() {
        dmnDecisionImpl.setDecisionLogic(decisionLogic);
        assertEquals(decisionLogic, dmnDecisionImpl.getDecisionLogic());
    }

    @Test(expected = NullPointerException.class)
    public void testSetDecisionLogicFailure() {
        dmnDecisionImpl.setDecisionLogic(null);
    }
}
