// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine.impl;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import org.camunda.bpm.dmn.engine.DmnDecision;
import org.camunda.bpm.dmn.engine.DmnDecisionLogic;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;

public class DmnDecisionImpl_toString_2393b88875_Test {

    private DmnDecisionTableImpl decisionTable;

    @BeforeEach
    public void setUp() {
        decisionTable = new DmnDecisionTableImpl();
    }

    @Test
    public void testToStringWithAllPropertiesSet() {
        decisionTable.setKey("key");
        decisionTable.setName("name");
        
        DmnDecision requiredDecision = mock(DmnDecision.class);
        decisionTable.setRequiredDecision(requiredDecision);
        
        DmnDecisionLogic decisionLogic = mock(DmnDecisionLogic.class);
        decisionTable.setDecisionLogic(decisionLogic);
        
        String expectedResult = "DmnDecisionTableImpl{ key= key, name= name, requiredDecision=" + requiredDecision + ", decisionLogic=" + decisionLogic + '}';
        assertEquals(expectedResult, decisionTable.toString());
    }

    @Test
    public void testToStringWithNoPropertiesSet() {
        String expectedResult = "DmnDecisionTableImpl{ key= null, name= null, requiredDecision=null, decisionLogic=null}";
        assertEquals(expectedResult, decisionTable.toString());
    }
}
