// Test generated by RoostGPT for test camunda-engine-unit using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.application;

import org.camunda.bpm.container.RuntimeContainerDelegate;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.MockitoJUnitRunner;

import static org.mockito.Mockito.times;

@RunWith(MockitoJUnitRunner.class)
public class AbstractProcessApplication_undeploy_e27144ff04_Test {

    private AbstractProcessApplication processApplication;

    @Mock
    private RuntimeContainerDelegate runtimeContainerDelegate;

    @Mock
    private ProcessApplicationLogger logger;

    @Before
    public void setup() {
        processApplication = new AbstractProcessApplication() {
            @Override
            public String getName() {
                return "testApplication";
            }
        };
        processApplication.LOG = logger;
        RuntimeContainerDelegate.INSTANCE.set(runtimeContainerDelegate);
    }

    @Test
    public void testUndeployWhenNotDeployed() {
        processApplication.isDeployed = false;

        processApplication.undeploy();

        Mockito.verify(logger, times(1)).notDeployed();
        Mockito.verify(runtimeContainerDelegate, times(0)).undeployProcessApplication(processApplication);
    }

    @Test
    public void testUndeployWhenDeployed() {
        processApplication.isDeployed = true;

        processApplication.undeploy();

        Mockito.verify(logger, times(0)).notDeployed();
        Mockito.verify(runtimeContainerDelegate, times(1)).undeployProcessApplication(processApplication);
    }
}
