// Test generated by RoostGPT for test camunda-engine-unit using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.application;

import org.camunda.bpm.engine.impl.util.ClassLoaderUtil;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

@SpringBootTest
public class AbstractProcessApplication_getProcessApplicationClassloader_0ddce9f147_Test {

    AbstractProcessApplication abstractProcessApplication;

    @BeforeEach
    public void setUp() {
        abstractProcessApplication = new AbstractProcessApplication() {
            @Override
            public String getName() {
                return "TestApplication";
            }
        };
    }

    @Test
    public void testGetProcessApplicationClassloaderSuccess() {
        ClassLoader classLoader = abstractProcessApplication.getProcessApplicationClassloader();
        assertNotNull(classLoader);
    }

    @Test
    public void testGetProcessApplicationClassloaderFailure() {
        AbstractProcessApplication nullAbstractProcessApplication = null;
        assertThrows(NullPointerException.class, () -> nullAbstractProcessApplication.getProcessApplicationClassloader());
    }
}
