// Test generated by RoostGPT for test camunda-engine-unit using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.application;

import org.camunda.bpm.impl.juel.jakarta.el.BeanELResolver;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertSame;

public class AbstractProcessApplication_getBeanElResolver_ce0b9b9279_Test {
    private AbstractProcessApplication abstractProcessApplication;

    @Before
    public void setUp() {
        abstractProcessApplication = Mockito.spy(AbstractProcessApplication.class);
    }

    @Test
    public void testGetBeanElResolverWhenResolverIsNull() {
        BeanELResolver beanELResolver = abstractProcessApplication.getBeanElResolver();
        assertNotNull("BeanELResolver should not be null", beanELResolver);
        assertSame("Should return the same instance of BeanELResolver on subsequent calls", 
            beanELResolver, abstractProcessApplication.getBeanElResolver());
    }

    @Test
    public void testGetBeanElResolverWhenResolverIsNotNull() {
        BeanELResolver initialBeanELResolver = new BeanELResolver();
        abstractProcessApplication.processApplicationBeanElResolver = initialBeanELResolver;
        BeanELResolver beanELResolver = abstractProcessApplication.getBeanElResolver();
        assertSame("Should return the initial instance of BeanELResolver when it's not null", 
            initialBeanELResolver, beanELResolver);
    }
}
