// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class DmnEngineException_DmnEngineException_a9d8ecca80_Test {

    @Mock
    Throwable throwable;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testDmnEngineExceptionWithMessage() {
        String message = "Test Message"; 
        DmnEngineException exception = new DmnEngineException(message, throwable);
        assertEquals(message, exception.getMessage());
    }

    @Test
    public void testDmnEngineExceptionWithCause() {
        String message = "Test Message"; 
        DmnEngineException exception = new DmnEngineException(message, throwable);
        assertEquals(throwable, exception.getCause());
    }

    @Test
    public void testDmnEngineExceptionWithEmptyMessage() {
        String message = ""; 
        DmnEngineException exception = new DmnEngineException(message, throwable);
        assertTrue(exception.getMessage().isEmpty());
    }

    @Test
    public void testDmnEngineExceptionWithNullMessage() {
        String message = null; 
        DmnEngineException exception = new DmnEngineException(message, throwable);
        assertEquals(null, exception.getMessage());
    }
}
