// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class DmnEngineException_DmnEngineException_cdf223cd9e_Test {

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testDmnEngineExceptionWithMessage() {
        String testMessage = "Test exception message";
        DmnEngineException exception = new DmnEngineException(testMessage);
        assertEquals(testMessage, exception.getMessage());
    }

    @Test
    public void testDmnEngineExceptionWithEmptyMessage() {
        String testMessage = "";
        DmnEngineException exception = new DmnEngineException(testMessage);
        assertEquals(testMessage, exception.getMessage());
    }
}
