// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class DmnEngineException_DmnEngineException_cdf223cd9e_Test {

    @Test
    public void testDmnEngineExceptionWithMessage() {
        String message = "Test Exception Message";
        DmnEngineException exception = new DmnEngineException(message);
        assertEquals(message, exception.getMessage());
    }

    @Test
    public void testDmnEngineExceptionWithEmptyMessage() {
        String message = "";
        DmnEngineException exception = new DmnEngineException(message);
        assertEquals(message, exception.getMessage());
    }
}
