// Test generated by RoostGPT for test Camunda-engine-dmn using AI Type Open AI and AI Model gpt-4

package org.camunda.bpm.dmn.engine;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class DmnEngineException_DmnEngineException_cdf223cd9e_Test {

    private DmnEngineException dmnEngineException;

    @BeforeEach
    public void setUp() {
        dmnEngineException = null;
    }

    @Test
    public void testDmnEngineException_withValidMessage() {
        String message = "Valid Exception Message";
        dmnEngineException = new DmnEngineException(message);
        assertEquals(message, dmnEngineException.getMessage());
    }

    @Test
    public void testDmnEngineException_withNullMessage() {
        String message = null;
        dmnEngineException = new DmnEngineException(message);
        assertEquals(message, dmnEngineException.getMessage());
    }
}
